const D=window.FOCO_DATA;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const LS={career:'foco:v12:career',done:'foco:v12:done',fav:'foco:v12:fav',errors:'foco:v12:errors',reasons:'foco:v12:reasons',writingDrafts:'foco:v14:writingDrafts',writingHistory:'foco:v14:writingHistory'};
const load=(k,def=[])=>{try{const v=localStorage.getItem(k);return v===null?def:JSON.parse(v)}catch{return def}};
const save=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const strip=s=>String(s??'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const unique=a=>[...new Set(a)];
const badDistractor=/A solução (técnica )?é correta independentemente|A solução depende exclusivamente da conveniência|em qualquer hipótese/i;
const curated=D.exercises.filter(q=>q.examCase&&q.contextType&&q.trap&&Array.isArray(q.optionAnalysis)&&q.opts?.length>=4&&!q.opts.some(o=>badDistractor.test(o)));
let currentCareer=load(LS.career,'prf-admin'); if(!D.careers.some(c=>c.id===currentCareer))currentCareer='prf-admin';
let currentLesson=null, practice=null, sim=null, timerHandle=null, simStartedAt=0;

const PROFILES=[
{id:'prf-admin',short:'PRF ADM',title:'PRF — Agente Administrativo',year:'2014',board:'FUNCAB',format:'60 questões • múltipla escolha',total:60,official:'https://www.gov.br/prf/pt-br/acesso-a-informacao/servidores/concursos-e-selecoes/editais-anteriores',analysis:'https://www.qconcursos.com/questoes-de-concursos/provas/funcab-2014-prf-agente-administrativo-01',dist:[['Português',12],['Direito Constitucional',7],['Ética e Conduta Pública',6],['Raciocínio Lógico',6],['Direito Administrativo',6],['Noções de Administração',6],['Arquivologia',6],['Informática',6],['Legislação PRF',5]],note:'A prova de 2014 continua sendo a última matriz administrativa listada oficialmente pela PRF. O peso é histórico; a legislação deve ser estudada na redação vigente.'},
{id:'pcdf',short:'PCDF',title:'PCDF — Agente de Polícia',year:'2021',board:'Cebraspe',format:'120 itens • Certo/Errado',total:120,official:'https://cdn.cebraspe.org.br/concursos/pc_df_20_agente/arquivos/PCDF_AGENTE_CB1_COMJUSTIFICATIVA.PDF',analysis:'https://www.qconcursos.com/questoes-de-concursos/provas/cespe-cebraspe-2021-pc-df-agente-de-policia-da-carreira-de-policia-civil-do-distrito-federal',dist:[['Português',20],['Informática',14],['Estatística',12],['Contabilidade',12],['Direito Administrativo',11],['Língua Inglesa',9],['Direito Penal',9],['Matemática e Raciocínio Lógico',8],['Direito Constitucional',8],['Processo Penal',8],['Conhecimentos sobre DF / RIDE',5],['Legislação PCDF',3],['Direitos Humanos',1]],note:'A prova de 2021 é a matriz de cobrança. Para o estudo atual, o Regimento Interno deve ser conferido pela norma vigente (Resolução PCDF nº 8/2025).'},
{id:'pcgo',short:'PCGO',title:'PCGO — Agente de Polícia',year:'2022',board:'Instituto AOCP',format:'80 questões • múltipla escolha',total:80,official:'https://goias.gov.br/administracao/edital-006-2022-concurso-pc-go-agente-escrivao-e-papiloscopista/',analysis:'https://www.qconcursos.com/questoes-de-concursos/provas/instituto-aocp-2022-pc-go-agente-de-policia',dist:[['Direito Penal',19],['Processo Penal',13],['Português',10],['Direito Constitucional',7],['Direito Administrativo',6],['Legislação Estadual — GO',6],['Raciocínio Lógico',5],['Realidade de Goiás',4],['Criminalística',4],['Medicina Legal',4],['Legislação Penal Especial',2]],note:'A prova objetiva de 2022 continua sendo a matriz de ingresso. Atos e avaliações posteriores do curso de formação são complemento e não substituem essa distribuição.'}
];
const profile=id=>PROFILES.find(p=>p.id===id), career=id=>D.careers.find(c=>c.id===id), lessons=id=>D.lessons.filter(l=>!id||(l.careers||[]).includes(id));
const done=()=>load(LS.done), fav=()=>load(LS.fav), errors=()=>load(LS.errors), reasons=()=>load(LS.reasons,{});
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2200)}
function progress(){const ids=done().filter(id=>D.lessons.some(l=>l.id===id));const pct=D.lessons.length?Math.round(ids.length/D.lessons.length*100):0;$('#globalProgress').style.width=pct+'%';$('#globalProgressLabel').textContent=pct+'%'}
function populateCareerSelects(){const html=D.careers.map(c=>`<option value="${c.id}">${c.name.replace(' — ',' ')}</option>`).join('');['globalCareer','learnCareer','practiceCareer'].forEach(id=>{const el=$('#'+id);el.innerHTML=html;el.value=currentCareer})}
function subjectsFor(id){return unique(lessons(id).map(l=>l.subject)).sort((a,b)=>a.localeCompare(b,'pt-BR'))}
function populateSubjects(select,careerId,all='Todas as matérias'){select.innerHTML=`<option value="">${all}</option>`+subjectsFor(careerId).map(s=>`<option>${s}</option>`).join('')}
function setCareer(id){currentCareer=id;save(LS.career,id);['globalCareer','learnCareer','practiceCareer'].forEach(x=>{if($('#'+x))$('#'+x).value=id});populateSubjects($('#learnSubject'),id);populateSubjects($('#practiceSubject'),id);renderHome();renderLearn();renderReview();toast('Objetivo alterado para '+career(id).name)}

function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${id}`));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#sidebar').classList.remove('open');window.scrollTo(0,0);if(id==='home')renderHome();if(id==='learn')renderLearn();if(id==='review')renderReview();if(id==='reference')renderReference();if(id==='simulations')renderSimCards();if(id==='writing')renderWriting()}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]')?.dataset.view;if(v){e.preventDefault();showView(v)}const lid=e.target.closest('[data-lesson]')?.dataset.lesson;if(lid)openLesson(lid);const fid=e.target.closest('[data-fav]')?.dataset.fav;if(fid){e.stopPropagation();toggleFav(fid)}});
$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
$('#globalCareer').onchange=e=>setCareer(e.target.value);$('#learnCareer').onchange=e=>setCareer(e.target.value);$('#practiceCareer').onchange=e=>setCareer(e.target.value);

function examSubjectCount(subject,id=currentCareer){const p=profile(id);if(!p)return null;let row=p.dist.find(([s])=>s===subject);if(!row&&id==='pcdf'&&subject==='Raciocínio Lógico')row=p.dist.find(([s])=>s==='Matemática e Raciocínio Lógico');if(!row&&id==='pcdf'&&subject==='Realidade do DF e Entorno')row=p.dist.find(([s])=>s==='Conhecimentos sobre DF / RIDE');return row?.[1]??null}
function renderHome(){const ls=lessons(currentCareer), d=done(), next=ls.find(l=>!d.includes(l.id))||ls[0], qcount=curated.filter(q=>q.careers.includes(currentCareer)).length, err=errors().filter(x=>x.career===currentCareer||x.careers?.includes(currentCareer));
$('#homeNext').innerHTML=next?`<span class="label">PRÓXIMA AULA</span><h3>${esc(next.title)}</h3><p>${esc(next.subject)} • ${next.minutes||45} min<br>${esc(next.summary)}</p><button class="text-btn card-action" data-lesson="${next.id}">Abrir aula →</button>`:'<h3>Trilha concluída</h3>';
$('#homePractice').innerHTML=`<span class="label">QUESTÕES CURADAS</span><div class="metric-line"><b>${qcount}</b><span>itens contextualizados<br>nesta trilha</span></div><p>O banco principal evita os distratores mais genéricos da versão anterior.</p><button class="text-btn card-action" data-view="practice">Iniciar treino →</button>`;
$('#homeReview').innerHTML=`<span class="label">REVISÃO</span><div class="metric-line"><b>${err.length}</b><span>erros salvos<br>para revisar</span></div><p>Volte nas questões em que o seu raciocínio falhou.</p><button class="text-btn card-action" data-view="review">Abrir revisão →</button>`;
const p=profile(currentCareer), max=Math.max(...p.dist.map(x=>x[1]));$('#homeExamFocus').innerHTML=p.dist.slice(0,6).reduce((arr,x,i)=>{const col=i<2?0:i<4?1:2;(arr[col]??=[]).push(x);return arr},[]).map((rows,i)=>`<article class="exam-focus-card"><span class="kicker">${i===0?'MAIOR PESO':i===1?'PESO INTERMEDIÁRIO':'COMPLEMENTO'}</span><h3>${p.short} • ${p.year}</h3>${rows.map(([s,n])=>`<div class="priority-row"><div>${s}<div class="mini-bar"><i style="width:${Math.round(n/max*100)}%"></i></div></div><b>${n}/${p.total}</b></div>`).join('')}</article>`).join('');progress()}

function lessonCard(l){const isDone=done().includes(l.id), isFav=fav().includes(l.id), n=examSubjectCount(l.subject,l.careers.includes(currentCareer)?currentCareer:l.careers[0]);return `<article class="lesson-card"><div class="lesson-card-top"><span class="subject-pill">${esc(l.subject)}</span><span class="status-pill ${isDone?'done':''}">${isDone?'Concluída':'Pendente'}</span></div><h3>${esc(l.title)}</h3><p>${esc(l.summary)}</p>${n!==null?`<div class="priority-badge">Última prova: ${n} item(ns) na matéria</div>`:''}<div class="lesson-card-meta"><span>${l.minutes||45} min</span><span>${l.quiz?.length||0} questões</span></div><div class="lesson-card-actions"><button class="btn secondary" data-lesson="${l.id}">Estudar</button><button class="icon-action ${isFav?'on':''}" data-fav="${l.id}" title="Salvar para revisão">☆</button></div></article>`}
function renderLearn(){const car=$('#learnCareer').value||currentCareer, sub=$('#learnSubject').value, term=($('#learnSearch').value||'').trim().toLowerCase();let ls=lessons(car).filter(l=>(!sub||l.subject===sub)&&(!term||(`${l.title} ${l.summary} ${l.subject}`).toLowerCase().includes(term)));$('#lessonList').innerHTML=ls.map(lessonCard).join('');$('#learnSummary').textContent=`${ls.length} aulas encontradas • ${subjectsFor(car).length} matérias na trilha`;}
$('#learnSubject').onchange=renderLearn;$('#learnSearch').oninput=renderLearn;
function toggleFav(id){let a=fav();a=a.includes(id)?a.filter(x=>x!==id):[...a,id];save(LS.fav,a);renderLearn();renderReview();if(currentLesson?.id===id)updateLessonFav();toast(a.includes(id)?'Aula salva para revisão':'Aula removida dos salvos')}
function updateLessonFav(){if(!currentLesson)return;$('#toggleFavorite').textContent=fav().includes(currentLesson.id)?'★ Salva para revisão':'☆ Salvar para revisão'}
function lessonPriority(l){const parts=(l.careers||[]).map(cid=>{const n=examSubjectCount(l.subject,cid);return n===null?'':`<span><b>${profile(cid)?.short}</b>: ${n}/${profile(cid)?.total} na matéria da última prova</span>`}).filter(Boolean);return parts.length?`<div class="last-exam-callout"><strong>Prioridade pela última prova</strong>${parts.join('<br>')}<br><small>Use como referência de tempo; o próximo edital pode mudar a distribuição.</small></div>`:''}
function openLesson(id){currentLesson=D.lessons.find(l=>l.id===id);if(!currentLesson)return;$('#lessonSubject').textContent=currentLesson.subject;$('#lessonTitle').textContent=currentLesson.title;$('#lessonMeta').textContent=`${currentLesson.track||currentLesson.careers.map(x=>career(x)?.name).join(' • ')} • ${currentLesson.minutes||45} min`;$('#lessonBody').innerHTML=lessonPriority(currentLesson)+currentLesson.body;renderLessonQuiz();updateLessonFav();$('#lessonResult').classList.add('hidden');$('#lessonDialog').showModal()}
$('#closeLesson').onclick=()=>$('#lessonDialog').close();$('#lessonDialog').addEventListener('click',e=>{if(e.target===$('#lessonDialog'))$('#lessonDialog').close()});$('#toggleFavorite').onclick=()=>currentLesson&&toggleFav(currentLesson.id);$('#completeLesson').onclick=()=>{if(!currentLesson)return;let a=done();if(!a.includes(currentLesson.id))a.push(currentLesson.id);save(LS.done,a);progress();renderLearn();renderHome();$('#completeLesson').textContent='✓ Aula concluída';toast('Aula marcada como concluída')};

function hash(s){let h=0;for(const c of String(s))h=((h<<5)-h)+c.charCodeAt(0)|0;return Math.abs(h)}
function normalizeQuestion(q,careerId){if(careerId!=='pcdf'&&!q._forceCE)return {...q,displayOpts:q.opts,displayCorrect:q.correct,displayPrompt:q.q};const trueItem=hash((q.id||q.q)+(q._forceCE?'cebraspe':''))%2===0;const correctText=q.opts[q.correct];const wrongs=q.opts.filter((_,i)=>i!==q.correct&&!badDistractor.test(q.opts[i]));const statement=trueItem?correctText:(wrongs[hash(q.id+'w')%Math.max(1,wrongs.length)]||q.opts.find((_,i)=>i!==q.correct));return {...q,displayOpts:['Certo','Errado'],displayCorrect:trueItem?0:1,displayPrompt:`${q._forceCE?'<span class="ce-command">Julgue o item a seguir, considerando a situação apresentada e a legislação/conceitos aplicáveis.</span>':''}<strong>${statement}</strong>`,cebStatement:statement,cebTrue:trueItem}}
function reasonKey(q,prefix){return prefix+':'+(q.id||strip(q.q))}
function saveReason(q,prefix,text){const r=reasons();r[reasonKey(q,prefix)]=text;save(LS.reasons,r)}
function readReason(q,prefix){return reasons()[reasonKey(q,prefix)]||''}
function selected(name){const x=document.querySelector(`input[name="${name}"]:checked`);return x?Number(x.value):null}
function questionMarkup(q,index,total,prefix,{showCorrection=false,locked=false}={}){const nq=normalizeQuestion(q,prefix.startsWith('sim-pcdf')||currentCareer==='pcdf'&&prefix.startsWith('practice')?'pcdf':q._career||currentCareer);const name=`${prefix}-answer`;const saved=prefix.startsWith('practice')?practice?.answers[index]:prefix.startsWith('sim')?sim?.answers[index]:null;const reason=prefix.startsWith('practice')?practice?.reasons[index]??readReason(q,prefix):prefix.startsWith('sim')?sim?.reasons[index]??'':readReason(q,prefix);const board=nq._bankLabel||(nq._career==='pcdf'||currentCareer==='pcdf'&&prefix.startsWith('practice')?'CEBRASPE':nq._career==='pcgo'?'AOCP':nq._career==='prf-admin'?'FUNCAB':strip(nq.examStyle||'QUESTÃO AUTORAL'));return `<article class="question-card" data-qindex="${index}"><div class="question-head"><div class="question-meta"><span class="meta-chip">${board}</span><span class="meta-chip">${esc(nq.subject)}</span><span class="meta-chip">${esc(nq.difficulty||'Intermediária')}</span></div><span class="question-number">Questão ${index+1} de ${total}</span></div><div class="question-body"><span class="case-label">${esc(nq.contextType||'SITUAÇÃO')}</span><div class="case-box">${nq.examCase||nq.context||''}</div>${nq.examCommand?`<p class="question-command">${nq.examCommand}</p>`:''}<div class="question-prompt">${nq.displayPrompt}</div><div class="options">${nq.displayOpts.map((o,i)=>`<label class="option"><input type="radio" name="${name}" value="${i}" ${saved===i?'checked':''} ${locked?'disabled':''}><span class="option-content"><b class="option-letter">${String.fromCharCode(65+i)}</b><span class="option-text">${esc(o)}</span></span></label>`).join('')}</div><div class="reason-box"><label>Explique por que você escolheu essa resposta</label><small>Registre o fato decisivo do enunciado, a regra/conceito usado e a pegadinha que você descartou.</small><textarea id="${prefix}-reason" ${locked?'readonly':''} placeholder="Escreva seu raciocínio antes de consultar a correção...">${esc(reason)}</textarea></div>${showCorrection?correctionMarkup(q,nq,saved,reason):''}<div class="question-actions"><button class="btn secondary" data-qnav="prev">← Anterior</button><div class="center-actions">${!locked&&!prefix.startsWith('sim')?'<button class="btn primary" data-correct-one>Corrigir esta questão</button>':''}<button class="btn secondary" data-qnav="next">Próxima →</button></div></div></div></article>`}
function correctionMarkup(q,nq,answer,reason){const ok=answer===nq.displayCorrect, originalCorrect=q.correct;let analyses=nq.displayOpts.length===2?[`A assertiva foi construída a partir de ${nq.cebTrue?'uma proposição correta':'um distrator incorreto'} do item-base.`,`No padrão Cebraspe, uma palavra que amplia ou restringe a regra pode alterar todo o julgamento.`]:(q.optionAnalysis||[]);return `<section class="correction"><div class="correction-head ${ok?'ok':'bad'}">${ok?'✓ Resposta correta':'✕ Resposta incorreta'} • Gabarito: ${String.fromCharCode(65+nq.displayCorrect)}</div><div class="correction-body"><h4>Seu raciocínio</h4><div class="user-reason">${esc(reason||'Você não registrou uma justificativa.')}</div><h4>Resolução comentada</h4><p>${esc(q.comment||q.concept||'Revise o conceito central da questão.')}</p>${q.modelReasoning?`<p><strong>Raciocínio-modelo:</strong> ${esc(q.modelReasoning)}</p>`:''}<h4>Análise das alternativas</h4><div class="analysis-list">${analyses.map((a,i)=>`<div class="analysis-item"><strong>${nq.displayOpts.length===2?(i===0?'Estrutura do item':'Atenção'):`${String.fromCharCode(65+i)})`}</strong> ${esc(a)}</div>`).join('')}</div>${q.trap?`<h4>Pegadinha</h4><div class="trap-box">${esc(q.trap)}</div>`:''}<h4>Fundamento para revisão</h4><p>${esc(q.foundation||q.review||'Volte à teoria da aula e confronte a regra aplicada.')}</p>${q.foundationUrl?`<a class="foundation-link" href="${q.foundationUrl}" target="_blank" rel="noopener">Abrir fonte de referência ↗</a>`:''}</div></section>`}
function saveError(q,nq,answer,reason,origin,careerId){let a=errors();const key=(q.id||strip(q.q))+':'+origin;const item={key,id:q.id,subject:q.subject,title:strip(q.q),context:strip(q.examCase||q.context),answer,correct:nq.displayCorrect,reason,comment:q.comment,trap:q.trap,foundation:q.foundation,foundationUrl:q.foundationUrl,career:careerId,origin,at:new Date().toISOString()};a=[item,...a.filter(x=>x.key!==key)].slice(0,250);save(LS.errors,a)}

function renderLessonQuiz(){const qs=(currentLesson.quiz||[]).slice(0,3);$('#lessonQuiz').innerHTML=qs.map((q,i)=>{const nq=normalizeQuestion(q,currentLesson.careers.includes(currentCareer)?currentCareer:currentLesson.careers[0]);return `<div class="lesson-q-wrap" data-lesson-q="${i}">${questionMarkup({...q,_career:currentCareer},i,qs.length,'lesson-'+i)}</div>`}).join('');$$('#lessonQuiz [data-correct-one]').forEach((b,i)=>b.onclick=()=>correctLessonQuestion(i));$$('#lessonQuiz [data-qnav]').forEach(b=>b.style.display='none')}
function correctLessonQuestion(i){const q=currentLesson.quiz[i], prefix='lesson-'+i,nq=normalizeQuestion(q,currentLesson.careers.includes(currentCareer)?currentCareer:currentLesson.careers[0]),ans=selected(`${prefix}-answer`),reason=$(`#${prefix}-reason`).value.trim();if(ans===null){toast('Marque uma alternativa antes de corrigir.');return}saveReason(q,prefix,reason);if(ans!==nq.displayCorrect)saveError(q,nq,ans,reason,'Aula: '+currentLesson.title,currentCareer);const wrap=$(`[data-lesson-q="${i}"]`);wrap.innerHTML=questionMarkup({...q,_career:currentCareer},i,currentLesson.quiz.slice(0,3).length,prefix,{showCorrection:true,locked:true});wrap.querySelectorAll('[data-qnav]').forEach(b=>b.style.display='none')}

function filteredPractice(){const car=$('#practiceCareer').value||currentCareer,sub=$('#practiceSubject').value;return curated.filter(q=>q.careers.includes(car)&&(!sub||q.subject===sub))}
$('#startPractice').onclick=()=>{const pool=shuffle(filteredPractice()),count=Math.min(Number($('#practiceCount').value),pool.length);if(!count){toast('Nenhuma questão neste filtro.');return}practice={career:$('#practiceCareer').value||currentCareer,items:pool.slice(0,count),index:0,answers:{},reasons:{},corrected:{}};$('#practiceSetup').classList.add('hidden');$('#practiceResult').classList.add('hidden');$('#practiceSession').classList.remove('hidden');renderPracticeQuestion()};
$('#practiceSubject').onchange=()=>{};$('#newPractice').onclick=()=>resetPractice();function resetPractice(){practice=null;$('#practiceSession').classList.add('hidden');$('#practiceSetup').classList.remove('hidden');$('#practiceResult').classList.add('hidden')}
function capturePractice(){if(!practice)return;const q=practice.items[practice.index],ans=selected('practice-answer'),reason=$('#practice-reason')?.value||'';if(ans!==null)practice.answers[practice.index]=ans;practice.reasons[practice.index]=reason;saveReason(q,'practice',reason)}
function renderPracticeQuestion(showCorrection=false){const q=practice.items[practice.index];$('#practiceQuestion').innerHTML=questionMarkup({...q,_career:practice.career},practice.index,practice.items.length,'practice',{showCorrection:showCorrection||!!practice.corrected[practice.index],locked:!!practice.corrected[practice.index]});bindPracticeActions();$('#practicePosition').textContent=`${practice.index+1} / ${practice.items.length}`;$('#practiceProgress').style.width=((practice.index+1)/practice.items.length*100)+'%';$('#practiceAnswered').textContent=Object.keys(practice.answers).length;$('#practiceCorrected').textContent=Object.keys(practice.corrected).length}
function bindPracticeActions(){$('#practiceQuestion [data-qnav="prev"]').onclick=()=>{capturePractice();if(practice.index>0){practice.index--;renderPracticeQuestion()}};$('#practiceQuestion [data-qnav="next"]').onclick=()=>{capturePractice();if(practice.index<practice.items.length-1){practice.index++;renderPracticeQuestion()}};const c=$('#practiceQuestion [data-correct-one]');if(c)c.onclick=()=>{capturePractice();const q=practice.items[practice.index],nq=normalizeQuestion(q,practice.career),ans=practice.answers[practice.index],reason=practice.reasons[practice.index]||'';if(ans===undefined){toast('Marque uma alternativa antes de corrigir.');return}practice.corrected[practice.index]=true;if(ans!==nq.displayCorrect)saveError(q,nq,ans,reason,'Questões',practice.career);renderPracticeQuestion(true);renderReview()}}
$('#finishPractice').onclick=()=>{capturePractice();let hits=0,answered=0;practice.items.forEach((q,i)=>{const nq=normalizeQuestion(q,practice.career),a=practice.answers[i];if(a!==undefined)answered++;if(a===nq.displayCorrect)hits++;else if(a!==undefined)saveError(q,nq,a,practice.reasons[i]||'','Questões',practice.career)});$('#practiceSession').classList.add('hidden');const pct=answered?Math.round(hits/answered*100):0;$('#practiceResult').classList.remove('hidden');$('#practiceResult').innerHTML=`<span class="kicker">RESULTADO</span><h2>${hits} acertos em ${answered} respondidas</h2><div class="result-numbers"><div><b>${pct}%</b><span>aproveitamento</span></div><div><b>${practice.items.length-answered}</b><span>em branco</span></div><div><b>${errors().filter(x=>x.origin==='Questões').length}</b><span>erros no caderno</span></div></div><button class="btn primary" id="practiceAgain">Nova sessão</button>`;$('#practiceAgain').onclick=resetPractice;renderReview()};

const SIMS=[
{id:'prf-cebraspe',careerId:'prf-admin',mode:'cebraspe',title:'PRF Administrativo — estilo Cebraspe',board:'CEBRASPE • TREINO DE ESTILO',count:60,format:'60 itens • Certo / Errado',scoring:'+1 / −1 / 0',desc:'Mesma matriz do PRF Administrativo, convertida em julgamento de itens com precisão conceitual, casos hipotéticos e risco de pontuação negativa.',featured:true},
{id:'prf-quadrix',careerId:'prf-admin',mode:'quadrix',title:'PRF Administrativo — estilo Quadrix',board:'QUADRIX • TREINO DE ESTILO',count:60,format:'60 questões • 5 alternativas',scoring:'+1 / 0',desc:'Mesma matriz do PRF Administrativo em múltipla escolha, com casos práticos, distratores plausíveis e comparação entre conceitos próximos.',featured:true},
{id:'prf-funcab',careerId:'prf-admin',mode:'funcab',title:'PRF Administrativo — referência histórica',board:'FUNCAB • PROVA 2014',count:30,format:'30 questões • 5 alternativas',scoring:'+1 / 0',desc:'Treino resumido preservando a referência histórica da última prova administrativa oficial da PRF.'},
{id:'pcdf',careerId:'pcdf',mode:'cebraspe',title:'PCDF Agente — diagnóstico',board:'CEBRASPE • 2021',count:40,format:'40 itens • Certo / Errado',scoring:'+1 / −1 / 0',desc:'40 itens contextualizados no padrão de julgamento da banca.'},
{id:'pcgo',careerId:'pcgo',mode:'aocp',title:'PCGO Agente — diagnóstico',board:'INSTITUTO AOCP • 2022',count:30,format:'30 questões • 5 alternativas',scoring:'+1 / 0',desc:'30 questões contextualizadas com maior peso para Penal e Processo Penal.'}
];
function renderSimCards(){if(sim&&!$('#simSession').classList.contains('hidden'))return;$('#simulationCards').classList.remove('hidden');$('#simulationCards').innerHTML=SIMS.map(s=>`<article class="sim-card ${s.featured?'featured-sim':''}"><div class="sim-card-head"><span class="board">${s.board}</span>${s.featured?'<span class="recommended">PRF ADM</span>':''}</div><h3>${s.title}</h3><p>${s.desc}</p><div class="sim-data"><span>${s.count} itens</span><span>${s.format}</span><span>Pontuação ${s.scoring}</span></div><button class="btn primary" data-start-sim="${s.id}">Iniciar simulado</button></article>`).join('');$$('[data-start-sim]').forEach(b=>b.onclick=()=>startSim(b.dataset.startSim))}
function weightedPool(careerId,count){const p=profile(careerId),all=curated.filter(q=>q.careers.includes(careerId)),chosen=[],used=new Set();const normalized=s=>{if(careerId==='pcdf'&&s==='Matemática e Raciocínio Lógico')return ['Matemática e Raciocínio Lógico','Raciocínio Lógico'];if(careerId==='pcdf'&&s==='Conhecimentos sobre DF / RIDE')return ['Conhecimentos sobre DF / RIDE','Realidade do DF e Entorno'];return [s]};p.dist.forEach(([sub,n])=>{const want=Math.max(1,Math.round(count*n/p.total));const cand=shuffle(all.filter(q=>normalized(sub).includes(q.subject)&&!used.has(q.id)));cand.slice(0,want).forEach(q=>{chosen.push(q);used.add(q.id)})});shuffle(all.filter(q=>!used.has(q.id))).slice(0,Math.max(0,count-chosen.length)).forEach(q=>chosen.push(q));return shuffle(chosen).slice(0,count)}
function simQuestion(q){if(!sim)return q;const base={...q,_career:sim.careerId||sim.id};if(sim.mode==='cebraspe')return {...base,_forceCE:true,_bankLabel:'CEBRASPE • CERTO/ERRADO',contextType:q.contextType||'SITUAÇÃO HIPOTÉTICA',examCommand:'Julgue o item conforme a situação e a regra aplicável.'};if(sim.mode==='quadrix')return {...base,_bankLabel:'QUADRIX • MÚLTIPLA ESCOLHA',contextType:q.contextType||'CASO PRÁTICO',examCommand:q.examCommand||'Considerando a situação apresentada, assinale a alternativa correta.'};if(sim.mode==='funcab')return {...base,_bankLabel:'FUNCAB • REFERÊNCIA 2014'};if(sim.mode==='aocp')return {...base,_bankLabel:'AOCP • 2022'};return base}
function startSim(id){const def=SIMS.find(x=>x.id===id),careerId=def.careerId||id,items=weightedPool(careerId,def.count);sim={...def,careerId,items,index:0,answers:{},reasons:{},review:false};$('#simulationCards').classList.add('hidden');$('.bank-lab')?.classList.add('hidden');$('.sim-section-title')?.classList.add('hidden');$('#simResult').classList.add('hidden');$('#simSession').classList.remove('hidden');$('#simBoard').textContent=def.board;$('#simTitle').textContent=def.title;simStartedAt=Date.now();clearInterval(timerHandle);timerHandle=setInterval(updateTimer,1000);updateTimer();renderSimQuestion()}
function fmtTime(ms){const s=Math.floor(ms/1000),m=Math.floor(s/60),r=s%60;return `${String(m).padStart(2,'0')}:${String(r).padStart(2,'0')}`}
function updateTimer(){if(!sim)return;const t=fmtTime(Date.now()-simStartedAt);$('#simTimer').textContent=t;$('#simTimeSmall').textContent=t}
function captureSim(){if(!sim)return;const ans=selected('sim-answer'),reason=$('#sim-reason')?.value||'';if(ans!==null)sim.answers[sim.index]=ans;sim.reasons[sim.index]=reason}
function renderSimQuestion(){const q=simQuestion(sim.items[sim.index]);$('#simQuestion').innerHTML=questionMarkup(q,sim.index,sim.items.length,'sim',{showCorrection:sim.review,locked:sim.review});$('#simPosition').textContent=`${sim.index+1} / ${sim.items.length}`;$('#simProgress').style.width=((sim.index+1)/sim.items.length*100)+'%';$('#simAnswered').textContent=Object.keys(sim.answers).length;const prev=$('#simQuestion [data-qnav="prev"]'),next=$('#simQuestion [data-qnav="next"]');prev.onclick=()=>{if(!sim.review)captureSim();if(sim.index>0){sim.index--;renderSimQuestion()}};next.onclick=()=>{if(!sim.review)captureSim();if(sim.index<sim.items.length-1){sim.index++;renderSimQuestion()}}}
$('#finishSim').onclick=()=>{if(!sim)return;captureSim();clearInterval(timerHandle);let hits=0,wrong=0,answered=0;sim.items.forEach((raw,i)=>{const q=simQuestion(raw),nq=normalizeQuestion(q,sim.careerId),a=sim.answers[i];if(a!==undefined){answered++;if(a===nq.displayCorrect)hits++;else wrong++}if(a!==nq.displayCorrect)saveError(q,nq,a??null,sim.reasons[i]||'',`Simulado ${sim.board}`,sim.careerId)});const blank=sim.items.length-answered,elapsed=Date.now()-simStartedAt,isRisk=sim.mode==='cebraspe',net=isRisk?hits-wrong:hits,pct=Math.round(hits/sim.items.length*100);sim.review=true;$('#simSession').classList.add('hidden');$('#simResult').classList.remove('hidden');$('#simResult').innerHTML=`<span class="kicker">RESULTADO • ${sim.board}</span><h2>${isRisk?`Pontuação líquida: ${net}`:`${hits} acertos em ${sim.items.length}`}</h2><div class="result-numbers"><div><b>${hits}</b><span>acertos</span></div><div><b>${wrong}</b><span>erros${isRisk?' (−1 cada)':''}</span></div><div><b>${blank}</b><span>em branco</span></div><div><b>${pct}%</b><span>acerto bruto</span></div><div><b>${fmtTime(elapsed)}</b><span>tempo total</span></div></div><p>${isRisk?'Neste treino Cebraspe, o erro retirou um ponto e a omissão valeu zero. Isso força você a decidir quando tem segurança suficiente para marcar.':'Neste treino de múltipla escolha, erros não retiram pontos. O foco é comparar distratores e localizar a única alternativa tecnicamente correta.'}</p><p>Os erros foram enviados ao Caderno de Erros. Na revisão, abra cada item para conferir resolução, pegadinha e fundamento.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn primary" id="reviewSim">Revisar prova</button><button class="btn secondary" id="closeSimResult">Voltar aos simulados</button></div>`;$('#reviewSim').onclick=()=>{sim.index=0;$('#simResult').classList.add('hidden');$('#simSession').classList.remove('hidden');$('#finishSim').classList.add('hidden');renderSimQuestion()};$('#closeSimResult').onclick=exitSim;renderReview()};
$('#exitSim').onclick=exitSim;function exitSim(){clearInterval(timerHandle);sim=null;$('#simSession').classList.add('hidden');$('#simResult').classList.add('hidden');$('#finishSim').classList.remove('hidden');$('#simulationCards').classList.remove('hidden');$('.bank-lab')?.classList.remove('hidden');$('.sim-section-title')?.classList.remove('hidden');renderSimCards()}



/* ===== V14 — OFICINA DE REDAÇÃO ===== */
const WRITING_BANKS={
  cebraspe:{name:'CEBRASPE',label:'Texto dissertativo conforme comando',source:'https://cdn.cebraspe.org.br/concursos/ANSA_26/arquivos/3969A00660D0B4D434998AC83CDA12E570D28CC2D67C47C6FDF6C58697C33FB1.html',tip:'Responda todos os aspectos do comando. Estrutura e conhecimento do tema precisam caminhar juntos; a modalidade escrita também é penalizada conforme regra do edital.'},
  quadrix:{name:'QUADRIX',label:'Dissertativo/argumentativo técnico ou atual',source:'https://ajuda.quadrix.org.br/pt-BR/articles/8185658-informacoes-sobre-a-prova-discursiva',tip:'Mostre domínio do conteúdo e raciocínio: explique, compare, relacione causas e efeitos e sustente a posição pedida. Critérios e linhas dependem do edital.'}
};
const WRITING_THEMES={
cebraspe:[
{id:'ceb-integridade',title:'Integridade pública e confiança social',stimulus:'A confiança nas instituições depende não apenas de controles formais, mas da conduta cotidiana dos agentes públicos e da capacidade de prevenir conflitos de interesse.',command:'Redija texto dissertativo acerca do papel da integridade na Administração Pública.',aspects:[{label:'relação entre ética, integridade e confiança nas instituições',keys:['ética','integridade','confiança','institui']},{label:'mecanismos de prevenção de conflitos de interesse e desvios',keys:['conflito','preven','controle','transpar']},{label:'responsabilidade individual do servidor na proteção do interesse público',keys:['servidor','responsab','interesse público','dever']}],keywords:['integridade','ética','confiança','transparência','servidor','interesse público'],axes:['cultura de integridade e legitimidade institucional','controles preventivos + responsabilidade funcional']},
{id:'ceb-digital',title:'Transformação digital, inclusão e proteção de dados',stimulus:'A digitalização de serviços públicos pode reduzir custos e tempo de atendimento, mas também pode ampliar exclusões e riscos relacionados ao tratamento de dados pessoais.',command:'Redija texto dissertativo sobre os desafios da transformação digital na Administração Pública.',aspects:[{label:'ganhos de eficiência e qualidade no atendimento',keys:['eficiência','atendimento','digital','agilidade']},{label:'riscos de exclusão digital e necessidade de acessibilidade',keys:['inclus','acess','desigual','exclus']},{label:'proteção de dados, segurança e responsabilidade estatal',keys:['dados','privacidade','segurança','responsab']}],keywords:['digital','eficiência','inclusão','dados','segurança','atendimento'],axes:['eficiência sem exclusão digital','proteção de dados e segurança institucional']},
{id:'ceb-ia',title:'Inteligência artificial e decisão administrativa',stimulus:'Sistemas de inteligência artificial já auxiliam triagens, análises e previsões na gestão pública. O ganho de eficiência, entretanto, não elimina a necessidade de transparência e controle humano.',command:'Redija texto dissertativo sobre o uso responsável de inteligência artificial na gestão pública.',aspects:[{label:'potenciais ganhos de produtividade e qualidade decisória',keys:['produt','eficiência','qualidade','decis']},{label:'riscos de opacidade, viés e tratamento inadequado de dados',keys:['viés','opacid','dados','risco']},{label:'necessidade de supervisão humana, transparência e responsabilização',keys:['supervis','transpar','responsab','humano']}],keywords:['inteligência artificial','eficiência','dados','transparência','responsabilidade','supervisão'],axes:['eficiência e apoio à decisão','governança, transparência e controle humano']},
{id:'ceb-documentos',title:'Gestão documental e direito de acesso à informação',stimulus:'A transparência pública depende de informação localizável, íntegra e preservada. Sem gestão documental, a publicidade pode existir apenas formalmente.',command:'Redija texto dissertativo sobre a importância da gestão documental para a transparência e a eficiência administrativa.',aspects:[{label:'organização, classificação e preservação de documentos públicos',keys:['document','classifica','preserva','arquivo']},{label:'relação entre gestão documental e acesso à informação',keys:['acesso','informação','transpar','publicidade']},{label:'efeitos da boa gestão sobre eficiência, memória e responsabilização',keys:['eficiência','memória','responsab','controle']}],keywords:['gestão documental','arquivo','informação','transparência','eficiência','preservação'],axes:['informação organizada como condição da transparência','eficiência, memória institucional e controle']},
{id:'ceb-contratacoes',title:'Contratações públicas, planejamento e sustentabilidade',stimulus:'A contratação pública não se resume à escolha do menor preço. Planejamento, gestão de riscos e consideração do ciclo de vida podem ampliar a eficiência e reduzir desperdícios.',command:'Redija texto dissertativo sobre planejamento e sustentabilidade nas contratações públicas.',aspects:[{label:'importância do planejamento da contratação',keys:['planejamento','necessidade','contrata','estudo']},{label:'gestão de riscos e busca do resultado mais vantajoso',keys:['risco','vantaj','resultado','eficiência']},{label:'sustentabilidade e responsabilidade no uso de recursos públicos',keys:['sustent','recursos','responsab','desperdício']}],keywords:['contratação','planejamento','risco','eficiência','sustentabilidade','recursos públicos'],axes:['planejamento e gestão de riscos','sustentabilidade e resultado público']},
{id:'ceb-seguranca-viaria',title:'Segurança viária como política pública integrada',stimulus:'Reduzir mortes e lesões no trânsito exige fiscalização, educação, infraestrutura, dados e coordenação entre órgãos. A dimensão administrativa é parte da capacidade estatal de entregar essa política.',command:'Redija texto dissertativo sobre a segurança viária como política pública e a importância do suporte administrativo para sua execução.',aspects:[{label:'caráter multidimensional da segurança viária',keys:['fiscaliza','educa','infraestrutura','dados','trânsito']},{label:'planejamento, logística e gestão de recursos na execução da política',keys:['planejamento','logística','recursos','gestão']},{label:'integração institucional e uso de evidências na tomada de decisão',keys:['integra','institui','evidência','decis']}],keywords:['segurança viária','trânsito','planejamento','logística','integração','dados'],axes:['política viária baseada em múltiplos instrumentos','capacidade administrativa e integração institucional']},
{id:'ceb-desinformacao',title:'Desinformação e comunicação institucional',stimulus:'Em ambientes digitais, informações falsas podem se espalhar mais rapidamente que comunicados oficiais e comprometer a confiança da população em serviços e instituições.',command:'Redija texto dissertativo sobre o papel da comunicação institucional no enfrentamento à desinformação.',aspects:[{label:'efeitos da desinformação sobre confiança e serviços públicos',keys:['desinform','confiança','serviço','institui']},{label:'dever de clareza, transparência e tempestividade da comunicação',keys:['clareza','transpar','comunica','tempest']},{label:'limites éticos: informar sem propaganda ou manipulação',keys:['ética','propaganda','manipula','impessoal']}],keywords:['desinformação','comunicação','transparência','confiança','ética','informação'],axes:['comunicação confiável como serviço público','transparência sem propaganda institucional']},
{id:'ceb-saude',title:'Saúde mental e qualidade do serviço público',stimulus:'Pressão por resultados, exposição a conflitos e rotinas intensas podem afetar a saúde mental de servidores, com reflexos sobre absenteísmo, segurança e qualidade do atendimento.',command:'Redija texto dissertativo sobre saúde mental no trabalho e qualidade do serviço público.',aspects:[{label:'relação entre condições de trabalho, saúde mental e desempenho',keys:['trabalho','saúde mental','desempenho','condiç']},{label:'medidas preventivas de gestão e apoio institucional',keys:['preven','apoio','gestão','capacita']},{label:'equilíbrio entre cuidado, responsabilidade e continuidade do serviço',keys:['responsab','continuidade','serviço','cuidado']}],keywords:['saúde mental','trabalho','gestão','prevenção','servidor','serviço público'],axes:['prevenção e ambiente organizacional saudável','continuidade e qualidade do serviço']}
],
quadrix:[
{id:'qua-teletrabalho',title:'Teletrabalho: produtividade, controle e integração',stimulus:'Modelos híbridos e remotos ampliaram a discussão sobre produtividade, controle de resultados e preservação da integração entre equipes públicas.',command:'Redija texto dissertativo-argumentativo posicionando-se sobre as condições necessárias para que o teletrabalho contribua para a eficiência no setor público.',aspects:[{label:'critérios de produtividade e avaliação por resultados',keys:['produt','resultado','meta','avalia']},{label:'comunicação, integração e coordenação da equipe',keys:['comunica','integra','equipe','coordena']},{label:'limites e riscos do modelo',keys:['risco','controle','isolamento','segurança']}],keywords:['teletrabalho','produtividade','resultado','equipe','controle','eficiência'],axes:['gestão por resultados','coordenação, segurança e limites do trabalho remoto']},
{id:'qua-lgpd',title:'Proteção de dados em serviços públicos digitais',stimulus:'A expansão de cadastros e serviços digitais aumenta a quantidade de dados pessoais tratada pela Administração.',command:'Discuta como o poder público pode conciliar inovação digital, prestação eficiente do serviço e proteção de dados pessoais.',aspects:[{label:'finalidade e necessidade no tratamento de dados',keys:['finalidade','necessidade','dados','tratamento']},{label:'segurança da informação e prevenção de incidentes',keys:['segurança','incidente','preven','acesso']},{label:'transparência e direitos do cidadão',keys:['transpar','direito','cidadão','informação']}],keywords:['dados pessoais','digital','segurança','transparência','serviço público','cidadão'],axes:['inovação guiada por finalidade e necessidade','segurança, transparência e direitos do cidadão']},
{id:'qua-burocracia',title:'Simplificação administrativa sem perda de controle',stimulus:'Exigências desnecessárias aumentam custos e tempo de atendimento, mas controles são essenciais para legalidade e proteção do interesse público.',command:'Apresente posição fundamentada sobre como simplificar procedimentos administrativos sem enfraquecer controles essenciais.',aspects:[{label:'eliminação de etapas sem valor público',keys:['simplifica','etapa','procedimento','burocra']},{label:'preservação de legalidade, rastreabilidade e controle',keys:['legalidade','controle','rastre','transpar']},{label:'uso de tecnologia e gestão de processos',keys:['tecnologia','processo','digital','gestão']}],keywords:['simplificação','controle','legalidade','processo','eficiência','tecnologia'],axes:['redução da burocracia inútil','controle baseado em risco e rastreabilidade']},
{id:'qua-sustentavel',title:'Sustentabilidade nas compras governamentais',stimulus:'O poder de compra do Estado pode induzir padrões de produção e consumo, mas decisões sustentáveis também precisam preservar economicidade e competição.',command:'Analise os benefícios e os cuidados necessários na incorporação de critérios de sustentabilidade às contratações públicas.',aspects:[{label:'benefícios ambientais e sociais',keys:['ambient','social','sustent']},{label:'economicidade, competição e planejamento',keys:['economic','compet','planejamento','preço']},{label:'critérios verificáveis e gestão contratual',keys:['critério','fiscaliza','contrato','gestão']}],keywords:['sustentabilidade','contratação','economicidade','planejamento','gestão','critério'],axes:['benefícios públicos do consumo sustentável','critérios objetivos e eficiência econômica']},
{id:'qua-acessibilidade',title:'Acessibilidade e inclusão no atendimento público',stimulus:'Serviços presenciais e digitais podem excluir cidadãos quando ignoram barreiras físicas, comunicacionais ou tecnológicas.',command:'Defenda medidas capazes de ampliar a acessibilidade dos serviços públicos sem comprometer eficiência e segurança.',aspects:[{label:'identificação das principais barreiras',keys:['barreira','acess','digital','física']},{label:'desenho inclusivo dos canais de atendimento',keys:['atendimento','inclus','canal','acesso']},{label:'capacitação e monitoramento da qualidade',keys:['capacita','monitor','qualidade','servidor']}],keywords:['acessibilidade','inclusão','atendimento','barreira','cidadão','serviço'],axes:['desenho inclusivo de serviços','capacitação e monitoramento']},
{id:'qua-redes',title:'Conduta do servidor em redes sociais',stimulus:'A presença de agentes públicos em redes sociais mistura esfera privada, deveres funcionais e percepção institucional.',command:'Analise os limites éticos da atuação de servidores públicos em redes sociais, considerando liberdade de expressão e deveres funcionais.',aspects:[{label:'liberdade de expressão e responsabilidade',keys:['liberdade','expressão','responsab']},{label:'sigilo, impessoalidade e imagem institucional',keys:['sigilo','impessoal','imagem','institui']},{label:'prudência e prevenção de conflito de interesses',keys:['prudência','conflito','interesse','ética']}],keywords:['redes sociais','servidor','ética','liberdade','responsabilidade','sigilo'],axes:['liberdade com responsabilidade funcional','sigilo, impessoalidade e prevenção de conflitos']},
{id:'qua-capacitacao',title:'Capacitação contínua e qualidade administrativa',stimulus:'Mudanças legais, tecnológicas e organizacionais tornam conhecimentos rapidamente obsoletos.',command:'Argumente sobre a importância da capacitação contínua dos servidores para eficiência, inovação e redução de erros administrativos.',aspects:[{label:'atualização técnica e normativa',keys:['atualiza','técnic','norma','capacita']},{label:'redução de erros e melhoria da qualidade',keys:['erro','qualidade','eficiência','serviço']},{label:'cultura de aprendizagem e inovação',keys:['aprendiz','inova','cultura','conhecimento']}],keywords:['capacitação','servidor','eficiência','erro','inovação','aprendizagem'],axes:['competência atualizada e redução de falhas','aprendizagem organizacional e inovação']},
{id:'qua-riscos',title:'Gestão de riscos e continuidade do serviço público',stimulus:'Falhas tecnológicas, eventos climáticos, indisponibilidade de fornecedores e incidentes de segurança podem interromper serviços essenciais.',command:'Explique por que a gestão de riscos deve integrar o planejamento administrativo e apresente elementos essenciais para continuidade do serviço.',aspects:[{label:'identificação e avaliação de riscos',keys:['risco','identifica','avalia']},{label:'prevenção, resposta e contingência',keys:['preven','conting','resposta','continuidade']},{label:'monitoramento e aprendizagem após incidentes',keys:['monitor','incidente','aprendiz','melhoria']}],keywords:['risco','planejamento','continuidade','contingência','monitoramento','serviço'],axes:['risco como parte do planejamento','contingência, monitoramento e aprendizagem']}
]};
let writingTimerHandle=null,writingSeconds=3600;
function writingTheme(){const bank=$('#writingBank')?.value||'cebraspe',id=$('#writingTheme')?.value;return (WRITING_THEMES[bank]||[]).find(t=>t.id===id)||(WRITING_THEMES[bank]||[])[0]}
function writingDrafts(){return load(LS.writingDrafts,{})}
function renderWriting(){const b=$('#writingBank');if(!b)return;const current=b.value||'cebraspe';const sel=$('#writingTheme');const prev=sel.value;sel.innerHTML=WRITING_THEMES[current].map(t=>`<option value="${t.id}">${esc(t.title)}</option>`).join('');if(WRITING_THEMES[current].some(t=>t.id===prev))sel.value=prev;renderWritingPrompt();renderWritingHistory();updateWritingMetrics()}
function renderWritingPrompt(){const t=writingTheme(),bank=WRITING_BANKS[$('#writingBank').value];if(!t||!bank)return;$('#writingPrompt').innerHTML=`<div class="prompt-bank"><b>${bank.name} • SIMULAÇÃO AUTORAL</b><span>${bank.label}</span></div><h3>${esc(t.title)}</h3><div class="stimulus">${esc(t.stimulus)}</div><p class="command">${esc(t.command)}</p><ol>${t.aspects.map(a=>`<li>${esc(a.label)}</li>`).join('')}</ol><span class="prompt-note">Configuração de treino: produza um texto de aproximadamente 25 a 30 linhas. Em prova real, siga exclusivamente o limite do edital e o comando da folha.</span>`;const draft=writingDrafts()[t.id];if(draft&&$('#writingText').value.trim()===''){$('#writingText').value=draft.text||'';$('#planThesis').value=draft.plan?.thesis||'';$('#planArg1').value=draft.plan?.arg1||'';$('#planArg2').value=draft.plan?.arg2||'';$('#planConclusion').value=draft.plan?.conclusion||'';updateWritingMetrics()}}
function writingWords(text){return (text.match(/[A-Za-zÀ-ÖØ-öø-ÿ0-9]+(?:['’\-][A-Za-zÀ-ÖØ-öø-ÿ0-9]+)*/g)||[])}
function writingParagraphs(text){return text.trim()?text.trim().split(/\n+/).map(x=>x.trim()).filter(Boolean):[]}
function updateWritingMetrics(){const text=$('#writingText')?.value||'',w=writingWords(text),pars=writingParagraphs(text);if($('#writingWords'))$('#writingWords').textContent=w.length;if($('#writingLines'))$('#writingLines').textContent=w.length?Math.max(text.split('\n').filter(x=>x.trim()).length,Math.ceil(w.length/10)):0;if($('#writingParagraphs'))$('#writingParagraphs').textContent=pars.length}
function saveWritingDraft(silent=false){const t=writingTheme();if(!t)return;const d=writingDrafts();d[t.id]={bank:$('#writingBank').value,text:$('#writingText').value,plan:{thesis:$('#planThesis').value,arg1:$('#planArg1').value,arg2:$('#planArg2').value,conclusion:$('#planConclusion').value},savedAt:Date.now()};save(LS.writingDrafts,d);if(!silent)toast('Rascunho salvo neste navegador')}
function skeletonForTheme(){const t=writingTheme();return `[INTRODUÇÃO]\nContextualize: ${t.title}. Delimite o problema e escreva sua tese em uma frase, indicando os dois eixos que serão desenvolvidos.\n\n[DESENVOLVIMENTO 1]\nApresente o primeiro argumento (${t.axes[0]}). Explique a relação de causa e efeito, acrescente fundamento ou exemplo e ligue o raciocínio à tese.\n\n[DESENVOLVIMENTO 2]\nDesenvolva o segundo eixo (${t.axes[1]}), sem repetir o parágrafo anterior. Demonstre por que esse ponto altera a análise do tema.\n\n[CONCLUSÃO]\nRetome a tese com outras palavras, sintetize os argumentos e responda diretamente ao comando. Acrescente encaminhamento apenas se ele for exigido.`}
function normText(s){return String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function countHits(text,keys){const n=normText(text);return keys.filter(k=>n.includes(normText(k))).length}
function analyzeWriting(text,t,bankId){const words=writingWords(text),pars=writingParagraphs(text),sent=text.split(/[.!?]+/).map(x=>x.trim()).filter(Boolean);const n=normText(text),issues=[];const add=(severity,title,why,fix,example='')=>issues.push({severity,title,why,fix,example});
const aspectStatus=t.aspects.map(a=>({label:a.label,ok:countHits(text,a.keys)>0}));const aspectCovered=aspectStatus.filter(x=>x.ok).length;
const themeHits=countHits(text,t.keywords);let adherence=Math.min(20,6+themeHits*2+aspectCovered*2);if(words.length<100)adherence=Math.min(adherence,10);if(themeHits<2)add('high','Aderência ao tema ainda fraca','Poucos conceitos centrais do tema aparecem de forma identificável.','Volte ao comando e faça cada parágrafo responder a uma parte dele. Não acrescente assunto lateral.',`Use os eixos: ${t.axes.join(' / ')}.`);
aspectStatus.filter(x=>!x.ok).forEach(x=>add('high','Aspecto do comando possivelmente não desenvolvido',x.label,'Inclua um trecho específico que responda a esse aspecto com explicação e consequência.'));
let structure=pars.length>=4?20:pars.length===3?15:pars.length===2?9:4;if(pars.length<4)add('high','Estrutura pouco controlada',`Foram identificados ${pars.length} parágrafo(s).`,'Para este treino, organize introdução, dois desenvolvimentos e conclusão. Depois ajuste se o edital/comando pedir outra estrutura.');
const first=pars[0]||'',last=pars[pars.length-1]||'';const thesisMarkers=['deve','é necessário','e necessario','é essencial','e essencial','torna-se','mostra-se','evidencia-se','sustenta-se','defende-se','exige','depende de'];const hasThesis=thesisMarkers.some(k=>normText(first).includes(normText(k)))||($('#planThesis')?.value||'').trim().length>8;let argument=hasThesis?8:4;if(!hasThesis)add('medium','Tese pouco explícita','A introdução não deixa clara, de forma facilmente detectável, a posição central que o texto defenderá.','Feche a introdução com uma afirmação que responda diretamente ao tema e antecipe a lógica dos desenvolvimentos.',`Ex.: “Nesse cenário, ${t.axes[0]} e ${t.axes[1]} constituem eixos decisivos para enfrentar a questão.”`);
const mid=pars.slice(1,-1);argument+=Math.min(12,mid.length*4+Math.min(4,countHits(mid.join(' '),['porque','pois','uma vez que','em razão','por isso','consequ','exemplo','dados','princípio','lei','norma'])));if(mid.length<2)add('medium','Argumentação concentrada demais','Há menos de dois parágrafos de desenvolvimento.','Separe os dois eixos. Em cada um, escreva: afirmação → explicação → fundamento/exemplo → consequência.');
const connectors=['além disso','ademais','nesse sentido','por outro lado','entretanto','contudo','todavia','assim','desse modo','portanto','logo','diante disso','consequentemente','primeiramente','em segundo lugar'];const connUsed=connectors.filter(k=>n.includes(normText(k)));let cohesion=Math.min(15,6+connUsed.length*2);if(connUsed.length<3)add('medium','Pouca sinalização de relações lógicas',`Foram identificados ${connUsed.length} conectivo(s) de progressão entre os mais usuais.`,'Use conectivos apenas quando a relação existir: adição, contraste, causa, consequência ou conclusão. Varie sem “encher” o texto.');
const conclusionMarkers=['portanto','diante disso','assim','desse modo','em síntese','em sintese','logo','por fim'];const hasConclusion=conclusionMarkers.some(k=>normText(last).includes(normText(k)))&&writingWords(last).length>=25;let conclusion=hasConclusion?10:5;if(!hasConclusion)add('medium','Conclusão pode fechar melhor o raciocínio','O último parágrafo não apresenta claramente um fechamento da tese ou está curto.','Retome a tese com outras palavras e responda ao comando. Não abra argumento novo na última linha.');
let language=15;const informal=[['eu acho','Substitua opinião pessoal explícita por formulação objetiva, sustentada por argumento.','“Observa-se que...” ou apresente diretamente a tese.'],['na minha opinião','Evite marcador pessoal desnecessário.','Apresente a posição como tese argumentada.'],['a gente','Registro informal.','Use “a sociedade”, “a Administração”, “os cidadãos” ou o sujeito exato.'],[' pra ','Contração informal.','Use “para”.'],[' tá ','Forma coloquial.','Use “está”.'],[' né','Marca de oralidade.','Retire e complete a afirmação.'],['tipo assim','Marca de oralidade.','Substitua por relação lógica objetiva.'],['coisa','Vocabulário vago.','Nomeie exatamente o fenômeno, medida, risco ou consequência.']];informal.forEach(([pat,fix,ex])=>{if(n.includes(normText(pat))){language-=2;add('high',`Registro inadequado: “${pat.trim()}”`,'Expressão coloquial ou vaga reduz precisão e formalidade.',fix,ex)}});
const mechanical=[];if(/\s+[,.;:!?]/.test(text))mechanical.push('há espaço indevido antes de sinal de pontuação');if(/[,;:](?=\S)/.test(text))mechanical.push('há pontuação sem espaço depois');if(/[!?.,]{2,}/.test(text))mechanical.push('há sinais de pontuação repetidos');if(/ {2,}/.test(text))mechanical.push('há espaços duplos');if(mechanical.length){language-=Math.min(4,mechanical.length);add('medium','Revisão mecânica necessária',mechanical.join('; ')+'.','Faça uma leitura exclusiva de pontuação e formatação antes de entregar.');}
const long=sent.map(x=>writingWords(x).length).filter(x=>x>45).length;if(long){language-=Math.min(3,long);add('medium','Períodos longos demais',`${long} período(s) ultrapassam aproximadamente 45 palavras.`,'Divida períodos quando houver muitas orações subordinadas. Uma ideia principal por período melhora clareza.');}
const stop=new Set('a o as os de da do das dos e em para por com que um uma uns umas no na nos nas ao aos à às se ser como mais mas ou sua seu suas seus é são foi foram isso esse essa este esta também já não sobre entre quando onde muito pela pelo pelos pelas'.split(' '));const freq={};writingWords(n).filter(w=>w.length>4&&!stop.has(w)).forEach(w=>freq[w]=(freq[w]||0)+1);const rep=Object.entries(freq).sort((a,b)=>b[1]-a[1]).filter(x=>x[1]>=6).slice(0,3);if(rep.length){language-=2;add('low','Repetição vocabular',`Palavras repetidas com frequência: ${rep.map(x=>`${x[0]} (${x[1]}x)`).join(', ')}.`,'Substitua apenas quando houver sinônimo preciso ou reestruture a frase; não troque termo técnico só para variar.');}
if(words.length<180)add('high','Texto curto para o treino',`Foram contadas ${words.length} palavras.`,'Desenvolva melhor as relações de causa, fundamento e consequência. Neste simulador, busque aproximadamente 25–30 linhas, sem enrolação.');if(words.length>420)add('medium','Texto muito extenso para a configuração de treino',`Foram contadas ${words.length} palavras.`,'Corte exemplos redundantes e repetições. Em prova, respeite exatamente a extensão determinada pelo edital.');
language=Math.max(2,language);argument=Math.min(20,argument);const total=Math.round(adherence+structure+argument+cohesion+language+conclusion);if(!issues.length)add('ok','Estrutura consistente no diagnóstico automático','Nenhum alerta estrutural importante foi detectado.','Faça ainda uma revisão humana de gramática, precisão conceitual e aderência fina ao comando.');return {score:Math.max(0,Math.min(100,total)),words:words.length,pars:pars.length,adherence,structure,argument,cohesion,language,conclusion,issues,aspectStatus,connectors:connUsed}}
function correctionLabel(score){return score>=85?'Muito consistente':score>=70?'Bom caminho':score>=55?'Estrutura intermediária':'Precisa de reescrita'}
function renderWritingCorrection(r,t,bankId){const bank=WRITING_BANKS[bankId];const metrics=[['Aderência ao comando',r.adherence,20],['Estrutura',r.structure,20],['Tese e argumentação',r.argument,20],['Coesão',r.cohesion,15],['Linguagem formal',r.language,15],['Conclusão',r.conclusion,10]];$('#writingCorrection').classList.remove('hidden');$('#writingCorrection').innerHTML=`<div class="correction-hero"><div class="correction-score"><b>${r.score}</b><span>/100 TREINO</span></div><div><span class="kicker">DIAGNÓSTICO • ${bank.name}</span><h2>${correctionLabel(r.score)}</h2><p>${bank.tip}</p><p class="correction-disclaimer">Pontuação heurística para treino. Não reproduz fórmula oficial de nenhum edital e não substitui correção humana.</p></div></div><div class="rubric-grid">${metrics.map(([n,v,m])=>`<div class="rubric-item"><div><span>${n}</span><b>${v}/${m}</b></div><i><em style="width:${Math.round(v/m*100)}%"></em></i></div>`).join('')}</div><section class="correction-section"><h3>Atendimento aos aspectos do tema</h3><div class="aspect-check">${r.aspectStatus.map(x=>`<span class="${x.ok?'':'miss'}"><b>${x.ok?'✓':'!'}</b>${esc(x.label)}</span>`).join('')}</div></section><section class="correction-section"><h3>Erros e como consertar</h3>${r.issues.map(i=>`<article class="correction-issue ${i.severity}"><strong>${esc(i.title)}</strong><p>${esc(i.why)}</p><p class="fix"><b>Como consertar:</b> ${esc(i.fix)}</p>${i.example?`<p><b>Exemplo de direção:</b> ${esc(i.example)}</p>`:''}</article>`).join('')}</section><section class="correction-section"><h3>Plano de reescrita</h3><div class="rewrite-guide"><p><b>Introdução:</b> delimite “${esc(t.title)}” e escreva uma tese que conecte ${esc(t.axes[0])} a ${esc(t.axes[1])}.</p><p><b>Desenvolvimento 1:</b> prove o eixo “${esc(t.axes[0])}” com mecanismo + fundamento + consequência.</p><p><b>Desenvolvimento 2:</b> desenvolva “${esc(t.axes[1])}” sem repetir o primeiro argumento.</p><p><b>Conclusão:</b> responda novamente ao comando em síntese. Acrescente proposta concreta apenas se o comando exigir.</p></div></section>`;$('#writingCorrection').scrollIntoView({behavior:'smooth',block:'start'})}
function renderWritingHistory(){const h=load(LS.writingHistory,[]);if(!$('#writingHistory'))return;$('#writingHistory').innerHTML=h.length?h.slice(0,6).map(x=>`<article class="history-card"><b>${x.score}/100</b><strong>${esc(x.title)}</strong><span>${esc(x.bank)} • ${new Date(x.at).toLocaleDateString('pt-BR')} • ${x.words} palavras</span></article>`).join(''):'<p style="color:var(--muted)">Nenhuma redação corrigida ainda.</p>'}
function resetWritingTimer(){clearInterval(writingTimerHandle);writingSeconds=3600;if($('#writingTimer'))$('#writingTimer').textContent='60:00'}
function tickWritingTimer(){writingSeconds--;const m=Math.max(0,Math.floor(writingSeconds/60)),s=Math.max(0,writingSeconds%60);$('#writingTimer').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(writingSeconds<=0){clearInterval(writingTimerHandle);toast('Tempo de redação encerrado')}}

function renderReview(){const d=done().filter(id=>D.lessons.some(l=>l.id===id)),e=errors(),f=fav();$('#reviewSummary').innerHTML=`<article class="review-stat"><b>${e.length}</b><span>questões no caderno de erros</span></article><article class="review-stat"><b>${f.length}</b><span>aulas salvas para revisão</span></article><article class="review-stat"><b>${d.length}/${D.lessons.length}</b><span>aulas concluídas</span></article>`;$('#reviewErrors').innerHTML=e.length?e.slice(0,40).map(x=>`<details class="error-card"><summary><div><span class="error-meta">${esc(x.origin)} • ${esc(x.subject)}</span><h4>${esc(x.title)}</h4></div><span>＋</span></summary><div class="error-detail"><p><strong>Contexto:</strong> ${esc(x.context||'—')}</p><p><strong>Sua justificativa:</strong> ${esc(x.reason||'Não registrada')}</p><p><strong>Correção:</strong> ${esc(x.comment||'Reveja a aula correspondente.')}</p>${x.trap?`<p><strong>Pegadinha:</strong> ${esc(x.trap)}</p>`:''}${x.foundation?`<p><strong>Fundamento:</strong> ${esc(x.foundation)}</p>`:''}${x.foundationUrl?`<a class="foundation-link" href="${x.foundationUrl}" target="_blank">Abrir fonte ↗</a>`:''}</div></details>`).join(''):'<div class="result-panel">Nenhum erro salvo ainda.</div>';const favLessons=f.map(id=>D.lessons.find(l=>l.id===id)).filter(Boolean);$('#reviewFavorites').innerHTML=favLessons.length?favLessons.slice(0,9).map(lessonCard).join(''):'<p style="color:var(--muted)">Nenhuma aula salva.</p>';const rem=lessons(currentCareer).filter(l=>!d.includes(l.id));$('#reviewNext').innerHTML=rem.slice(0,6).map(lessonCard).join('')}
$('#clearErrors').onclick=()=>{if(confirm('Deseja apagar todo o Caderno de Erros?')){save(LS.errors,[]);renderReview();renderHome()}};

function renderReference(){renderProfiles();renderSyllabus();renderSources()}
function renderProfiles(){$('#examProfiles').innerHTML=PROFILES.map(p=>{const max=Math.max(...p.dist.map(x=>x[1]));return `<article class="exam-profile"><div class="exam-profile-head"><div><span class="kicker">${p.short} • ${p.year}</span><h3>${p.title}</h3><p>${p.board} • ${p.format}</p></div><div class="exam-total">${p.total}</div></div><div class="exam-bars">${p.dist.map(([s,n])=>`<div class="exam-bar-row"><div class="exam-bar-label"><span>${s}</span><b>${n}</b></div><div class="exam-bar-line"><i style="width:${Math.round(n/max*100)}%"></i></div></div>`).join('')}</div><div class="exam-note">${p.note}</div><div class="exam-links"><a class="btn secondary compact" href="${p.official}" target="_blank" rel="noopener">Fonte oficial ↗</a><a class="text-btn" href="${p.analysis}" target="_blank" rel="noopener">Análise da distribuição ↗</a></div></article>`}).join('')}
function renderSyllabus(){$('#syllabusList').innerHTML=D.syllabus.map(s=>`<section class="syllabus-career"><span class="kicker">${esc(s.title)}</span><h3>${esc(s.base)}</h3><p>${esc(s.update)}</p>${s.subjects.map(x=>`<details class="syllabus-subject"><summary>${esc(x.name)} • ${x.items.length} blocos</summary><ul>${x.items.map(i=>`<li>${esc(i)}</li>`).join('')}</ul></details>`).join('')}</section>`).join('')}
function renderSources(){const extra=[...PROFILES.map(p=>({title:`${p.title} — fonte da última prova`,url:p.official,tag:'PROVA OFICIAL'})),{title:'PCDF — Regimento Interno (Resolução nº 8/2025)',url:'https://www.sinj.df.gov.br/sinj/Norma/dbe1096798f04ffcbefd5ec1b3cc1e87/pcdf_cspc_res_08_2025_rep.html',tag:'NORMA VIGENTE'},{title:'Lei nº 14.133/2021 — Licitações e Contratos',url:'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm',tag:'LEI SECA'},{title:'Cebraspe — exemplo recente de prova por itens C/E e critério +1/−1/0',url:'https://cdn.cebraspe.org.br/concursos/ANSA_26/arquivos/3969A00660D0B4D434998AC83CDA12E570D28CC2D67C47C6FDF6C58697C33FB1.html',tag:'PERFIL DE BANCA'},{title:'Quadrix — características oficiais da prova objetiva',url:'https://ajuda.quadrix.org.br/pt-BR/articles/8185616-informacoes-sobre-a-prova-objetiva',tag:'PERFIL DE BANCA'},{title:'Cebraspe — critérios recentes de prova discursiva',url:'https://cdn.cebraspe.org.br/concursos/ANSA_26/arquivos/3969A00660D0B4D434998AC83CDA12E570D28CC2D67C47C6FDF6C58697C33FB1.html',tag:'REDAÇÃO / DISCURSIVA'},{title:'Quadrix — informações oficiais sobre prova discursiva',url:'https://ajuda.quadrix.org.br/pt-BR/articles/8185658-informacoes-sobre-a-prova-discursiva',tag:'REDAÇÃO / DISCURSIVA'}],seen=new Set(),list=[...extra,...D.sources].filter(x=>x.url&&!seen.has(x.url)&&seen.add(x.url));$('#sourceList').innerHTML=list.map(s=>`<article class="source-card"><strong>${esc(s.title)}</strong><span>${esc(s.tag||'FONTE')}</span><a href="${s.url}" target="_blank" rel="noopener">Abrir fonte ↗</a></article>`).join('')}



$('#writingBank').onchange=()=>{$('#writingText').value='';['planThesis','planArg1','planArg2','planConclusion'].forEach(id=>$('#'+id).value='');renderWriting()};
$('#writingTheme').onchange=()=>{$('#writingText').value='';['planThesis','planArg1','planArg2','planConclusion'].forEach(id=>$('#'+id).value='');renderWritingPrompt();updateWritingMetrics()};
$('#randomWritingTheme').onclick=()=>{const bank=$('#writingBank').value,themes=WRITING_THEMES[bank],current=$('#writingTheme').value,others=themes.filter(t=>t.id!==current),pick=(others.length?others:themes)[Math.floor(Math.random()*(others.length||themes.length))];$('#writingTheme').value=pick.id;$('#writingText').value='';['planThesis','planArg1','planArg2','planConclusion'].forEach(id=>$('#'+id).value='');renderWritingPrompt();updateWritingMetrics()};
$('#writingText').oninput=updateWritingMetrics;
$('#insertSkeleton').onclick=()=>{if($('#writingText').value.trim()&&!confirm('O editor já contém texto. Deseja substituir pelo esqueleto?'))return;$('#writingText').value=skeletonForTheme();updateWritingMetrics();toast('Esqueleto inserido — substitua os marcadores pelo seu texto')};
$('#saveWriting').onclick=()=>saveWritingDraft(false);
$('#clearWriting').onclick=()=>{if(confirm('Limpar redação e planejamento deste tema?')){$('#writingText').value='';['planThesis','planArg1','planArg2','planConclusion'].forEach(id=>$('#'+id).value='');$('#writingCorrection').classList.add('hidden');updateWritingMetrics();resetWritingTimer()}};
$('#startWritingTimer').onclick=()=>{resetWritingTimer();writingTimerHandle=setInterval(tickWritingTimer,1000);toast('Cronômetro de 60 minutos iniciado')};
$('#correctWriting').onclick=()=>{const text=$('#writingText').value.trim(),t=writingTheme(),bankId=$('#writingBank').value;if(text.length<80){toast('Escreva um texto maior antes de corrigir');return}saveWritingDraft(true);const r=analyzeWriting(text,t,bankId);renderWritingCorrection(r,t,bankId);let h=load(LS.writingHistory,[]);h.unshift({score:r.score,title:t.title,bank:WRITING_BANKS[bankId].name,at:Date.now(),words:r.words});save(LS.writingHistory,h.slice(0,20));renderWritingHistory()};

function init(){populateCareerSelects();populateSubjects($('#learnSubject'),currentCareer);populateSubjects($('#practiceSubject'),currentCareer);$('#learnCareer').value=currentCareer;$('#practiceCareer').value=currentCareer;renderHome();renderLearn();renderReview();renderSimCards();renderWriting();progress()}
init();
