const D=window.FOCO_DATA,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],LS={fav:"foco:v8:fav",done:"foco:v8:done",reason:"foco:v10:reason",errors:"foco:v10:errors"};
const get=k=>{try{return JSON.parse(localStorage.getItem(k)||"[]")}catch{return[]}},set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let currentLesson=null,exerciseSet=[],currentSim=null,simSet=[];const lessons=()=>D.lessons,career=id=>D.careers.find(c=>c.id===id),fits=(l,id)=>!id||(l.careers||[]).includes(id);
const EXAM_PROFILES=[
{id:'prf-admin',short:'PRF ADM',title:'PRF — Agente Administrativo',year:'2014',date:'Último concurso administrativo oficial listado pela PRF',board:'FUNCAB',format:'60 questões • múltipla escolha',total:60,official:'https://www.gov.br/prf/pt-br/acesso-a-informacao/servidores/concursos-e-selecoes/editais-anteriores',analysis:'https://www.qconcursos.com/questoes-de-concursos/provas/funcab-2014-prf-agente-administrativo-01',top:['Português — 12/60','Direito Constitucional — 7/60','Ética — 6/60'],topics:['Interpretação de textos','Significação contextual de palavras','Lei 8.112 e improbidade em redação vigente','Organização da Administração e agentes públicos','Arquivologia: gestão, temporalidade e preservação','Segurança da informação e internet'],distribution:[['Português',12],['Direito Constitucional',7],['Ética e Conduta Pública',6],['Raciocínio Lógico',6],['Direito Administrativo',6],['Noções de Administração',6],['Arquivologia',6],['Informática',6],['Legislação PRF',5]],note:'A prova de 2014 continua sendo a última matriz administrativa. Em 2026, use o peso dessa prova, mas estude a lei vigente: Lei 14.133/2021 no lugar da antiga Lei 8.666/1993 como regime geral de licitações.'},
{id:'pcdf',short:'PCDF',title:'PCDF — Agente de Polícia',year:'2021',date:'Aplicada em 22/08/2021',board:'Cebraspe',format:'120 itens • Certo/Errado',total:120,official:'https://cdn.cebraspe.org.br/concursos/pc_df_20_agente/arquivos/PCDF_AGENTE_CB1_COMJUSTIFICATIVA.PDF',analysis:'https://www.qconcursos.com/questoes-de-concursos/provas/cespe-cebraspe-2021-pc-df-agente-de-policia-da-carreira-de-policia-civil-do-distrito-federal',top:['Português — 20/120','Estatística — 12/120','Contabilidade — 12/120'],topics:['Interpretação e reescrita de textos','Estatística descritiva e inferência','Balanço patrimonial e DRE','Lei 8.112, atos, poderes e responsabilidade do Estado','Informática: redes, VPN, banco de dados e programação','RIDE/DF','Penal, Processo Penal e Constitucional'],distribution:[['Português',20],['Estatística',12],['Contabilidade',12],['Direito Administrativo',11],['Língua Inglesa',9],['Direito Penal',9],['Matemática e Raciocínio Lógico',8],['Direito Constitucional',8],['Processo Penal',8],['Conhecimentos sobre DF / RIDE',5],['Legislação PCDF',3],['Informática',14],['Direitos Humanos',1]],note:'Na prova de 2021, o regimento então vigente foi cobrado. Em 2026, o Regimento Interno atual é o aprovado pela Resolução PCDF nº 8/2025; Decreto 30.490/2009 deve aparecer apenas como referência histórica da prova antiga.'},
{id:'pcgo',short:'PCGO',title:'PCGO — Agente de Polícia',year:'2022',date:'Aplicada em 10/12/2022',board:'Instituto AOCP',format:'80 questões • múltipla escolha',total:80,official:'https://goias.gov.br/administracao/edital-006-2022-concurso-pc-go-agente-escrivao-e-papiloscopista/',analysis:'https://www.qconcursos.com/questoes-de-concursos/provas/instituto-aocp-2022-pc-go-agente-de-policia',top:['Direito Penal — 19/80','Processo Penal — 13/80','Português — 10/80'],topics:['Legislação penal especial','Crimes contra patrimônio, vida, dignidade sexual e Administração','Inquérito, provas, ação penal, competência e nulidades','Interpretação, sintaxe, pronomes e pontuação','Legislação do Estado de Goiás','Criminalística: local de crime, cadeia de custódia e documentoscopia','Medicina Legal: traumatologia, asfixiologia e sexologia'],distribution:[['Direito Penal',19],['Processo Penal',13],['Português',10],['Direito Constitucional',7],['Direito Administrativo',6],['Legislação Estadual — GO',6],['Raciocínio Lógico',5],['Realidade de Goiás',4],['Criminalística',4],['Medicina Legal',4],['Legislação Penal Especial',2]],note:'A prova objetiva de 2022 continua sendo a matriz de ingresso. As avaliações de curso de formação publicadas depois servem como complemento, não substituem o peso da prova objetiva.'}
];
const EXAM_MIRRORS=[
{id:'espelho-prf',title:'Espelho da última prova — PRF Administrativo',meta:'PRF 2014',level:'Distribuição real',desc:'60 questões autorais respeitando a distribuição da última prova FUNCAB.',careers:['prf-admin'],count:60,distribution:Object.fromEntries(EXAM_PROFILES[0].distribution)},
{id:'espelho-pcdf',title:'Espelho da última prova — PCDF Agente',meta:'PCDF 2021',level:'Cebraspe C/E',desc:'120 itens autorais adaptados ao formato Certo/Errado, com a distribuição da prova de 2021.',careers:['pcdf'],count:120,mode:'ce',distribution:Object.fromEntries(EXAM_PROFILES[1].distribution)},
{id:'espelho-pcgo',title:'Espelho da última prova — PCGO Agente',meta:'PCGO 2022',level:'Distribuição real',desc:'80 questões autorais com o peso de matérias da prova AOCP de 2022.',careers:['pcgo'],count:80,distribution:Object.fromEntries(EXAM_PROFILES[2].distribution)}
];
const ALL_SIMS=[...EXAM_MIRRORS,...D.simulados];
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===`view-${id}`));$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view===id));$('#sidebar').classList.remove('open');window.scrollTo(0,0);if(id==='favorites')renderFavorites();if(id==='study')renderStudy();if(id==='materials')renderLessons();if(id==='sources')renderSources();if(id==='syllabus')renderSyllabus();if(id==='last-exam')renderExamProfiles();if(id==='errors')renderErrors()}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]')?.dataset.view;if(v){e.preventDefault();showView(v)}const l=e.target.closest('[data-lesson]')?.dataset.lesson;if(l)openLesson(l);const f=e.target.closest('[data-favorite]')?.dataset.favorite;if(f){toggleFav(f);e.stopPropagation()}const c=e.target.closest('[data-career]')?.dataset.career;if(c){showView('materials');$('#materialCareerFilter').value=c;renderLessons()}});$('#menuBtn').onclick=()=>$('#sidebar').classList.toggle('open');
function stats(id){const ls=lessons().filter(l=>fits(l,id));return {lessons:ls.length,questions:ls.reduce((n,l)=>n+(l.quiz?.length||0),0),subjects:new Set(ls.map(l=>l.subject)).size}}
function examProfile(id){return EXAM_PROFILES.find(x=>x.id===id)}
function examSubjectInfo(l){const out=[];(l.careers||[]).forEach(cid=>{const p=examProfile(cid);if(!p)return;let row=p.distribution.find(([sub])=>sub===l.subject);if(!row&&cid==='pcdf'&&l.subject==='Raciocínio Lógico')row=p.distribution.find(([sub])=>sub==='Matemática e Raciocínio Lógico');if(!row&&cid==='pcdf'&&l.subject==='Realidade do DF e Entorno')row=p.distribution.find(([sub])=>sub==='Conhecimentos sobre DF / RIDE');if(row)out.push({short:p.short,count:row[1],total:p.total,year:p.year})});return out}
function examBadge(l){const a=examSubjectInfo(l);return a.map(x=>`<span class="tag exam-tag">${x.short}: ${x.count}/${x.total} na última prova</span>`).join('')}
function examLessonBlock(l){const a=examSubjectInfo(l);if(!a.length)return '';return `<div class="last-exam-callout"><strong>🎯 Prioridade pela última prova</strong>${a.map(x=>`<span><b>${x.short} ${x.year}</b> — esta matéria teve ${x.count} de ${x.total} itens/questões.</span>`).join('')}<small>O conteúdo abaixo deve ser estudado com esse peso de prioridade. Questões internas são autorais, no estilo da última prova.</small></div>`}
function renderExamProfiles(){const cards=EXAM_PROFILES.map(p=>{const max=Math.max(...p.distribution.map(x=>x[1]));return `<section class="exam-profile"><div class="exam-profile-head"><div><span class="tag amber">${p.short} • ${p.year}</span><h2>${p.title}</h2><p>${p.date} • <strong>${p.board}</strong> • ${p.format}</p></div><div class="exam-total"><b>${p.total}</b><span>itens/questões</span></div></div><div class="exam-top">${p.top.map(x=>`<span>★ ${x}</span>`).join('')}</div><div class="exam-bars">${p.distribution.map(([sub,n])=>`<div class="exam-bar"><div><span>${sub}</span><b>${n}</b></div><i><em style="width:${Math.max(5,Math.round(n/max*100))}%"></em></i></div>`).join('')}</div><div class="exam-topics"><strong>Assuntos que merecem prioridade</strong><ul>${p.topics.map(t=>`<li>${t}</li>`).join('')}</ul></div><div class="update-box">${p.note}</div><div class="exam-links"><a class="btn ghost" href="${p.official}" target="_blank" rel="noopener">Fonte/prova oficial ↗</a><a class="btn soft" href="${p.analysis}" target="_blank" rel="noopener">Raio-X da prova ↗</a></div></section>`}).join('');$('#lastExamList').innerHTML=cards;$('#examSnapshot').innerHTML=EXAM_PROFILES.map(p=>`<article class="mini-card exam-snapshot-card"><span class="tag amber">${p.short} • ${p.year}</span><h3>${p.board}</h3><p>${p.format}</p><div class="exam-snapshot-top">${p.top.map(x=>`<span>${x}</span>`).join('')}</div><button class="btn ghost" data-view="last-exam">Ver o que caiu →</button></article>`).join('')}

function careerCard(c){const s=stats(c.id);return `<article class="career-card"><div class="career-icon">${c.icon}</div><div><span class="card-kicker">${c.badge}</span><h3>${c.name}</h3><p>${c.desc}</p><div class="career-meta"><span>${s.lessons} aulas</span><span>${s.subjects} matérias</span><span>${s.questions} questões</span></div><button class="btn ghost" data-career="${c.id}">Abrir trilha →</button></div></article>`}
function renderCareers(){$('#homeCareers').innerHTML=D.careers.map(careerCard).join('');$('#careerList').innerHTML=D.careers.map(careerCard).join('')}
function lessonCard(l){const fav=get(LS.fav).includes(l.id),done=get(LS.done).includes(l.id);return `<article class="lesson-card ${done?'done':''}"><div class="lesson-top"><span class="tag blue">${l.subject}</span><button class="favorite ${fav?'on':''}" data-favorite="${l.id}" aria-label="Favoritar">★</button></div><h3>${l.title}</h3><p>${l.summary}</p><div class="meta"><span class="tag">${l.track}</span><span class="tag">${l.minutes||30} min</span><span class="tag green">Aula + atividade + ${l.quiz?.length||0} questões</span>${examBadge(l)}</div><button class="btn primary" data-lesson="${l.id}">${done?'Revisar aula':'Estudar agora'} →</button></article>`}
function populate(){const cs=D.careers.map(c=>`<option value="${c.id}">${c.name}</option>`).join(''),subs=[...new Set(lessons().map(l=>l.subject))].sort((a,b)=>a.localeCompare(b,'pt-BR')).map(s=>`<option>${s}</option>`).join('');$('#materialCareerFilter').innerHTML='<option value="">Todas as trilhas</option>'+cs;$('#exerciseCareerFilter').innerHTML='<option value="">Todas as trilhas</option>'+cs;$('#materialSubjectFilter').innerHTML='<option value="">Todas as matérias</option>'+subs;$('#exerciseSubjectFilter').innerHTML='<option value="">Todas as matérias</option>'+subs}
function renderLessons(){const car=$('#materialCareerFilter').value,sub=$('#materialSubjectFilter').value,list=lessons().filter(l=>fits(l,car)&&(!sub||l.subject===sub));$('#lessonList').innerHTML=list.map(lessonCard).join('');const feature=lessons().filter(l=>['prf-leg-1','pcdf-l2','go-leg-1','port-1','adm-3','pen-6'].includes(l.id));$('#featuredLessons').innerHTML=(feature.length?feature:lessons().slice(0,6)).map(lessonCard).join('');$('#librarySummary').innerHTML=`<span><b>${list.length}</b> aulas</span><span><b>${new Set(list.map(l=>l.subject)).size}</b> matérias</span><span><b>${list.reduce((n,l)=>n+l.quiz.length,0)}</b> questões nas aulas</span><span><b>${D.exercises.filter(x=>!car||(x.careers||[]).includes(car)).length}</b> exercícios no banco</span>`}
$('#materialCareerFilter').onchange=renderLessons;$('#materialSubjectFilter').onchange=renderLessons;
function toggleFav(id){let a=get(LS.fav);a=a.includes(id)?a.filter(x=>x!==id):[...a,id];set(LS.fav,a);renderLessons();renderFavorites()}
function renderFavorites(){const a=get(LS.fav),list=lessons().filter(l=>a.includes(l.id));$('#favoriteList').innerHTML=list.map(lessonCard).join('');$('#favoriteEmpty').classList.toggle('hidden',list.length>0)}

function esc(v){return String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]))}
function reasonMap(){try{return JSON.parse(localStorage.getItem(LS.reason)||'{}')}catch{return {}}}
function reasonKey(q,p){return `${p}:${q.id||q.q}`}
function savedReason(q,p){return reasonMap()[reasonKey(q,p)]||''}
function saveReason(q,p,value){const m=reasonMap();m[reasonKey(q,p)]=value;localStorage.setItem(LS.reason,JSON.stringify(m))}
document.addEventListener('input',e=>{const t=e.target.closest('textarea[data-reason-id]');if(!t)return;saveReason({id:t.dataset.reasonId,q:t.dataset.reasonId},t.dataset.reasonPrefix,t.value)});
function guideFor(q){return D.subjectGuides?.[q.subject]||{summary:'Revise conceito, requisitos, aplicação e exceções antes de decidir.',exam:'A banca costuma trocar regra, exceção e consequência.',foundation:'Conteúdo programático e fonte oficial vigente.',url:''}}
function questionAnswer(q){return String.fromCharCode(65+q.correct)}
function selectedIndex(p,i){const s=$(`input[name="${p}-q${i}"]:checked`);return s?Number(s.value):null}
function optionBreakdown(q){return q.opts.map((o,j)=>`<li class="${j===q.correct?'right-opt':'wrong-opt'}"><b>${String.fromCharCode(65+j)}) ${esc(o)}</b><span>${esc(q.optionAnalysis?.[j]||(j===q.correct?q.comment:`Esta alternativa não corresponde ao conceito central. ${q.comment}`))}</span></li>`).join('')}
function fullCorrection(q,i,p){const sel=selectedIndex(p,i),ok=sel===q.correct,reason=savedReason(q,p).trim(),g=guideFor(q);return `<div class="correction-head ${ok?'ok':'bad'}"><div><b>${ok?'✓ Você acertou':'✕ Resposta a revisar'}</b><span>Gabarito ${questionAnswer(q)}${sel===null?' • você não marcou alternativa':` • sua resposta ${String.fromCharCode(65+sel)}`}</span></div><span class="tag ${ok?'green':'amber'}">${q.subject}</span></div><div class="student-answer-review"><strong>Seu raciocínio antes da correção</strong><p>${reason?esc(reason):'<em>Você não escreveu a justificativa. Na próxima, tente explicar a regra antes de corrigir.</em>'}</p></div><div class="deep-explanation"><h5>Por que a resposta é essa?</h5><p>${esc(q.comment)}</p><p><strong>Conceito central:</strong> ${esc(q.concept||q.comment)}</p></div><div class="model-reasoning"><h5>Resposta-modelo para o seu caderno</h5><p>${esc(q.modelReasoning||q.comment)}</p></div><div class="option-analysis"><h5>Análise alternativa por alternativa</h5><ol>${optionBreakdown(q)}</ol></div><div class="foundation-box"><h5>Onde revisar</h5><p><strong>Fundamento/base:</strong> ${esc(q.foundation||g.foundation)}</p><p><strong>Como a banca cobra:</strong> ${esc(q.howExam||g.exam)}</p>${q.foundationUrl||g.url?`<a href="${q.foundationUrl||g.url}" target="_blank" rel="noopener">Abrir fonte/base de revisão ↗</a>`:''}</div>`}
function errorList(){try{return JSON.parse(localStorage.getItem(LS.errors)||'[]')}catch{return []}}
function saveError(q,i,p,context){const sel=selectedIndex(p,i);if(sel===q.correct)return;let list=errorList(),key=`${context}:${q.id||q.q}`;list=list.filter(x=>x.key!==key);list.unshift({key,id:q.id,subject:q.subject,q:q.q,opts:q.opts,correct:q.correct,selected:sel,reason:savedReason(q,p),comment:q.comment,concept:q.concept,modelReasoning:q.modelReasoning,foundation:q.foundation,examStyle:q.examStyle,when:new Date().toISOString(),context});localStorage.setItem(LS.errors,JSON.stringify(list.slice(0,200)))}
function renderErrors(){const list=errorList();$('#errorEmpty')?.classList.toggle('hidden',list.length>0);if($('#errorsSummary'))$('#errorsSummary').innerHTML=`<span><b>${list.length}</b> questões para revisar</span><span><b>${new Set(list.map(x=>x.subject)).size}</b> matérias com erro</span>`;if($('#errorNotebook'))$('#errorNotebook').innerHTML=list.map((x,i)=>`<article class="error-entry"><header><div><span class="tag amber">${esc(x.subject)}</span><span class="tag">${esc(x.examStyle||'Concurso')}</span></div><small>${new Date(x.when).toLocaleDateString('pt-BR')}</small></header><h3>${i+1}. ${x.q}</h3><div class="error-grid"><div><strong>Sua resposta</strong><p>${x.selected===null?'Não respondeu':String.fromCharCode(65+x.selected)+') '+esc(x.opts[x.selected])}</p></div><div><strong>Gabarito</strong><p>${String.fromCharCode(65+x.correct)}) ${esc(x.opts[x.correct])}</p></div></div><div class="student-answer-review"><strong>Seu raciocínio</strong><p>${x.reason?esc(x.reason):'<em>Sem justificativa registrada.</em>'}</p></div><div class="deep-explanation"><strong>Correção</strong><p>${esc(x.comment)}</p><p><b>Conceito:</b> ${esc(x.concept||'')}</p></div><div class="model-reasoning"><strong>Como eu deveria explicar</strong><p>${esc(x.modelReasoning||x.comment)}</p></div><div class="foundation-box"><strong>Base para revisão</strong><p>${esc(x.foundation||'')}</p></div><button class="btn soft" data-remove-error="${esc(x.key)}">✓ Marcar como revisado</button></article>`).join('')}
document.addEventListener('click',e=>{const b=e.target.closest('[data-remove-error]');if(!b)return;let l=errorList().filter(x=>x.key!==b.dataset.removeError);localStorage.setItem(LS.errors,JSON.stringify(l));renderErrors()});
function qhtml(q,i,p){const g=guideFor(q),reason=savedReason(q,p);return `<article class="question exam-question"><div class="question-meta"><span class="tag amber">${esc(q.examStyle||'Estilo concurso')}</span><span class="tag">${esc(q.difficulty||'Intermediária')}</span><span class="tag blue">${esc(q.subject)}</span></div><div class="exam-context">${q.context||''}</div><h4><span>Questão ${i+1}</span>${q.q}</h4><div class="options">${q.opts.map((o,j)=>`<label class="option"><input type="radio" name="${p}-q${i}" value="${j}"><span><b>${String.fromCharCode(65+j)})</b> ${esc(o)}</span></label>`).join('')}</div><div class="reasoning-box"><label for="reason-${p}-${i}"><strong>✍️ Explique seu raciocínio antes de corrigir</strong><small>Escreva o conceito, regra, artigo ou lógica que faz você acreditar que sua alternativa é a correta. Não precisa escrever bonito; o objetivo é mostrar como você pensou.</small></label><textarea id="reason-${p}-${i}" data-reason-id="${esc(q.id||q.q)}" data-reason-prefix="${p}" rows="4" placeholder="Ex.: marquei esta alternativa porque... O conceito central é... A regra diz que...">${esc(reason)}</textarea></div><details class="theory-hint"><summary>📚 Relembrar a teoria antes de responder</summary><div><p>${esc(g.summary)}</p><p><strong>Como costuma cair:</strong> ${esc(g.exam)}</p><p><strong>Base de estudo:</strong> ${esc(g.foundation)}</p></div></details><div class="answer-note hidden deep-correction" data-answer="${i}"></div></article>`}
function openLesson(id){const l=lessons().find(x=>x.id===id);if(!l)return;currentLesson=l;$('#lessonCareer').textContent=l.track+' • '+l.subject;$('#lessonTitle').textContent=l.title;$('#lessonMeta').textContent=`${l.subject} • ${l.minutes||30} min • aula + leitura + atividade`;$('#lessonBody').innerHTML=examLessonBlock(l)+l.body;$('#lessonQuiz').innerHTML=l.quiz.map((q,i)=>qhtml(q,i,'lesson')).join('');$('#lessonQuizCount').textContent=`${l.quiz.length} questões`;$('#lessonQuizResult').classList.add('hidden');$('#lessonDialog').showModal()}
$('#closeLesson').onclick=()=>$('#lessonDialog').close();$('#showLessonAnswers').onclick=()=>currentLesson?.quiz.forEach((q,i)=>{const b=$(`#lessonQuiz [data-answer="${i}"]`);b.classList.remove('hidden');b.innerHTML=fullCorrection(q,i,'lesson')});
$('#finishLesson').onclick=()=>{if(!currentLesson)return;let hits=0;currentLesson.quiz.forEach((q,i)=>{const sel=selectedIndex('lesson',i),ok=sel===q.correct;if(ok)hits++;else saveError(q,i,'lesson','Aula: '+currentLesson.title);const b=$(`#lessonQuiz [data-answer="${i}"]`);b.classList.remove('hidden');b.classList.toggle('error',!ok);b.innerHTML=fullCorrection(q,i,'lesson')});const r=$('#lessonQuizResult');r.classList.remove('hidden');r.innerHTML=`<strong>Resultado: ${hits}/${currentLesson.quiz.length}</strong><br><small>${hits===currentLesson.quiz.length?'Ótimo. Agora releia suas justificativas e confirme se você acertou sabendo.':'Os erros foram enviados ao Caderno de Erros. Revise a explicação e tente escrever a regra com suas palavras.'}</small>`;let d=get(LS.done);if(!d.includes(currentLesson.id)){d.push(currentLesson.id);set(LS.done,d)}updateProgress();renderLessons()};
function pool(){const car=$('#exerciseCareerFilter').value,sub=$('#exerciseSubjectFilter').value;return D.exercises.filter(x=>(!car||x.careers.includes(car))&&(!sub||x.subject===sub))}
function renderExercises(){const p=[...pool()].sort(()=>Math.random()-.5),count=Math.min(Number($('#exerciseCount').value||20),p.length);exerciseSet=p.slice(0,count);$('#exerciseQuiz').innerHTML=exerciseSet.map((q,i)=>qhtml(q,i,'ex')).join('');$('#exerciseCounter').textContent=`${exerciseSet.length} sorteadas • ${p.length} disponíveis neste filtro`;$('#exerciseResult').classList.add('hidden')}
$('#resetExercises').onclick=renderExercises;['#exerciseCareerFilter','#exerciseSubjectFilter','#exerciseCount'].forEach(s=>$(s).onchange=renderExercises);$('#finishExercises').onclick=()=>{let hits=0;exerciseSet.forEach((q,i)=>{const sel=selectedIndex('ex',i),ok=sel===q.correct;if(ok)hits++;else saveError(q,i,'ex','Banco de exercícios');const b=$(`#exerciseQuiz [data-answer="${i}"]`);b.classList.remove('hidden');b.classList.toggle('error',!ok);b.innerHTML=fullCorrection(q,i,'ex')});const r=$('#exerciseResult');r.classList.remove('hidden');r.innerHTML=`<strong>${hits}/${exerciseSet.length} acertos • ${exerciseSet.length?Math.round(hits/exerciseSet.length*100):0}%</strong><br><small>Não olhe só a porcentagem: compare sua justificativa com a resposta-modelo. Erros foram salvos no Caderno de Erros.</small>`;renderErrors()};
function renderSimulados(){$('#simuladoList').innerHTML=ALL_SIMS.map(x=>`<article class="mini-card"><div class="mini-card-top"><span class="tag amber">${x.meta}</span><span class="tag blue">${x.level}</span></div><h3>${x.title}</h3><p>${x.desc}</p><button class="btn ghost" data-sim="${x.id}">Iniciar simulado →</button></article>`).join('');$$('[data-sim]').forEach(b=>b.onclick=()=>openSim(b.dataset.sim))}
function openSim(id){currentSim=ALL_SIMS.find(x=>x.id===id);let p=D.exercises.filter(x=>{const c=!currentSim.careers?.length||currentSim.careers.some(a=>x.careers.includes(a)),s=!currentSim.subjects?.length||currentSim.subjects.includes(x.subject);return c&&s});if(currentSim.distribution){simSet=[];Object.entries(currentSim.distribution).forEach(([sub,n])=>{let c=p.filter(q=>q.subject===sub);if(!c.length&&currentSim.careers?.includes('pcdf')&&sub==='Matemática e Raciocínio Lógico')c=p.filter(q=>['Matemática e Raciocínio Lógico','Raciocínio Lógico'].includes(q.subject));if(!c.length&&currentSim.careers?.includes('pcdf')&&sub==='Conhecimentos sobre DF / RIDE')c=p.filter(q=>['Conhecimentos sobre DF / RIDE','Realidade do DF e Entorno'].includes(q.subject));simSet.push(...[...c].sort(()=>Math.random()-.5).slice(0,Math.min(n,c.length)))});simSet=simSet.sort(()=>Math.random()-.5)}else simSet=[...p].sort(()=>Math.random()-.5).slice(0,Math.min(currentSim.count,p.length));if(currentSim.mode==='ce')simSet=simSet.map((q,i)=>{const trueItem=i%2===0,wrong=q.opts.find((_,j)=>j!==q.correct)??q.opts[0],statement=trueItem?q.opts[q.correct]:wrong;return {...q,q:`${q.q}<br><small class="ce-statement">Julgue a afirmação: <strong>${statement}</strong></small>`,opts:['Certo','Errado'],correct:trueItem?0:1,comment:`${q.comment} • Item autoral adaptado ao formato Cebraspe.`}});$('#simTitle').textContent=currentSim.title;$('#simMeta').textContent=`${simSet.length} questões • ${currentSim.desc}`;$('#simQuiz').innerHTML=simSet.map((q,i)=>qhtml(q,i,'sim')).join('');$('#simResult').classList.add('hidden');$('#simDialog').showModal()}
$('#closeSim').onclick=()=>$('#simDialog').close();$('#finishSim').onclick=()=>{let hits=0;simSet.forEach((q,i)=>{const sel=selectedIndex('sim',i),ok=sel===q.correct;if(ok)hits++;else saveError(q,i,'sim','Simulado: '+(currentSim?.title||''));const b=$(`#simQuiz [data-answer="${i}"]`);b.classList.remove('hidden');b.classList.toggle('error',!ok);b.innerHTML=fullCorrection(q,i,'sim')});const r=$('#simResult');r.classList.remove('hidden');r.innerHTML=`<strong>${hits}/${simSet.length} • ${simSet.length?Math.round(hits/simSet.length*100):0}%</strong><br><small>Revise principalmente os itens em que sua justificativa não conseguiu explicar a regra. Os erros foram salvos.</small>`;renderErrors()};
function renderSyllabus(){$('#syllabusList').innerHTML=D.syllabus.map(s=>`<section class="syllabus-career"><div class="syllabus-head"><span class="tag amber">BASE OFICIAL</span><h2>${s.title}</h2><p><strong>${s.base}</strong></p><div class="update-box">⚠ ${s.update}</div></div><div class="syllabus-subjects">${s.subjects.map(x=>`<details class="syllabus-subject"><summary><span>☑</span><strong>${x.name}</strong><small>${x.items.length} blocos</small></summary><ul>${x.items.map(i=>`<li>✓ ${i}</li>`).join('')}</ul></details>`).join('')}</div></section>`).join('')}
function renderSources(){const extra=[...EXAM_PROFILES.map(p=>({title:`${p.title} — prova/portal oficial`,url:p.official,tag:'PROVA OFICIAL',kind:'exam'})),{title:'PCDF — Regimento Interno vigente (Resolução nº 8/2025)',url:'https://www.sinj.df.gov.br/sinj/Norma/dbe1096798f04ffcbefd5ec1b3cc1e87/pcdf_cspc_res_08_2025_rep.html',tag:'ATUALIZAÇÃO 2026',kind:'law'},{title:'Lei nº 14.133/2021 — Licitações e Contratos',url:'https://www.planalto.gov.br/ccivil_03/_ato2019-2022/2021/lei/l14133.htm',tag:'ATUALIZAÇÃO 2026',kind:'law'}];const seen=new Set();const list=[...extra,...D.sources].filter(x=>!seen.has(x.url)&&seen.add(x.url));$('#sourceList').innerHTML=list.map(s=>`<article class="mini-card source-card"><span class="tag blue">${s.tag||'OFICIAL'}</span><h3>${s.title}</h3><p>${s.kind==='exam'?'Última prova/página oficial usada como matriz de cobrança.':'Use esta fonte para conferir edital, vigência e redação atual.'}</p><a class="btn ghost source-link" href="${s.url}" target="_blank" rel="noopener">Abrir fonte ↗</a></article>`).join('')}
function updateProgress(){const d=get(LS.done).filter(id=>lessons().some(l=>l.id===id)),p=lessons().length?Math.round(d.length/lessons().length*100):0;$('#globalProgress').style.width=p+'%';$('#globalProgressLabel').textContent=`${p}% • ${d.length}/${lessons().length} aulas`}
function renderStudy(){const done=get(LS.done),rem=lessons().filter(l=>!done.includes(l.id));$('#studySummary').innerHTML=[["Aulas concluídas",done.filter(id=>lessons().some(l=>l.id===id)).length],["Aulas restantes",rem.length],["Favoritos",get(LS.fav).length]].map(([a,b])=>`<article class="mini-card"><span class="eyebrow">PROGRESSO</span><h3>${b}</h3><p>${a}</p></article>`).join('');$('#studyPlans').innerHTML=D.studyPlans.map(p=>`<article class="mini-card plan-card"><span class="tag amber">PLANO</span><h3>${p.title}</h3><p>${p.desc}</p><ol>${p.steps.map(s=>`<li>${s}</li>`).join('')}</ol></article>`).join('');$('#studyLessons').innerHTML=(rem.length?rem.slice(0,9):lessons().slice(0,9)).map(lessonCard).join('')}
if($('#clearErrors'))$('#clearErrors').onclick=()=>{if(confirm('Limpar todo o Caderno de Erros?')){localStorage.removeItem(LS.errors);renderErrors()}};
function init(){renderCareers();populate();renderLessons();renderFavorites();renderExercises();renderSimulados();renderSyllabus();renderStudy();renderSources();renderExamProfiles();renderErrors();updateProgress()}init();
